### ISSUE TITLE
Implement paper_trail for audit trail

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#10]
This does not need to happen just yet, but very soon.

https://github.com/airblade/paper_trail

**Comment by kgf** [comment]
OK, now would be a good time !
This should be on the person, item, event models at a minimum.

**Comment by Spandana-Sai** [comment]
Work in progress @kgf

**Comment by kgf** [comment]
You're amazing, thanks for all your efforts.
