### ISSUE TITLE
Create AdminUser in Rails Console

### ISSUE THREAD

**Issue by edarsey** [ReadyResponder/ReadyResponder#107]
Hi I was checking out the README.md file and I haven't yet been able to create an admin user in the Rails console as mentioned. Could I get a little help with that so that I can look into the functionality of the rest of the app? I am looking to help contribute, and develop skills through this project.
Thanks, 
Eric

**Comment by kgf** [comment]
Sorry I did not see your issue earlier.
Have you been able to create a user ? In Rails console. can you do `User.first` ? If this has the user you created, you will need to associate them with a role. 

```
me=User.first
manager = Role.where(:name => "Manager")
me.roles << manager
```

If this corrects this issue, an improvement to the docs could be your first PR, which would be awesome! 
Thanks for your interest,
Kevin

**Comment by kgf** [comment]
@edarsey Did this resolve your issue ?

**Comment by kgf** [comment]
I think the best solution to this might be to set the first user to be admin. This would also mean that the setup should create the manager role if needed as well.

**Comment by kgf** [comment]
There is now enough code in the `seeds.rb` to create the admin user, and spit out the password.
While the seeds.rb could use additional attention, this ticket is resolved.

I'm also closing #26
