### ISSUE TITLE
Create a Vagrantfile

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#108]
This will allow folks to use Vagrant to contribute to Lims

**Comment by kgf** [comment]
This is not a top priority, but if it speaks to you....

**Comment by cesc1989** [comment]
Hey, @kgf I was skimming through the issues list and found this. Is this still a thing? I use vagrant for my local environment and provision the machine with ansible. If you take a look to .gitignore you'd see I've ignored a bunch of files for this purpose.

I can unignore them and document how to use those files for this project. Let me know.

**Comment by kgf** [comment]
I think many people use vagrant for local development. It would be nice to have that documented, in case others wanted to try it.

I want to make it as easy as possible for others to help !
Thanks
Kevin

**Comment by cesc1989** [comment]
OK. I'll do it.
