### ISSUE TITLE
Put enough data into seed db to support demo in development environment

### ISSUE THREAD

**Issue by houhoulis** [ReadyResponder/ReadyResponder#110]
People asked me for a demo at the http://bostonrb.org Project Night tonight, but I have no event, skills, etc. in my local db.

**Comment by houhoulis** [comment]
cc @david135  😺

**Comment by kgf** [comment]
@houhoulis do you think this would include the requirements of #107 creating an admin user ?

**Comment by kgf** [comment]
There have been recent improvements to the `seeds.rb` so a first step in this would be to simply start with a fresh install, and see what was missing. For the purposes of Hacktoberfest, I would accept a PR that listed the deficiencies, especially if there was a corresponding issue created.

**Comment by KaraAJC** [comment]
I'd like to try this out! 

To confirm: I'll be beefing up the `seeds.rb` file so that upon a fresh install and seed of the data, someone could run the app and see all the features of the app with a good set of fake data and understand what the app does.

**Comment by kgf** [comment]
That is exactly correct. Thanks!

**Comment by kgf** [comment]
@KaraAJC Do you have any updates or questions ?

**Comment by kgf** [comment]
We just had a request from a fellow developer to ensure we have timecards as seeds

**Comment by KaraAJC** [comment]
ok! I plan on pushing up a PR for this issue tonite, I'll make sure that's
in.

[image: photo]
*Kara Carrell | She/Her*
Web Developer | Communitechie
m:773-382-8220 | e:KaraAJC@gmail.com
<http://us.linkedin.com/in/KaraAJC>  <http://twitter.com/KaraAJC>
<http://about.me/KaraAJC>  <http://github.com/KaraAJC>

**Comment by kgf** [comment]
That's great news, thanks

**Comment by kgf** [comment]
Hello, @KaraAJC . Are you having any success. Anything we can help with ?

**Comment by KaraAJC** [comment]
Hi Thanks for checking in! I'm actually trying to setup the database, and though I've used postgres before, I'm not sure what the following refers to:

> Ensure you have a user for the database
> ```
> sudo -i -u postgres
> createuser -P --interactive <database-username>
> exit
> ```

when I run the first line, my response is: 

```
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
```
I already have a db for $USER, would that be sufficient?

**Comment by KaraAJC** [comment]
I got the db created and seeded, reviewing what data is empty in Active Admin, and gonna make a list of seeds to create

**Comment by KaraAJC** [comment]
@kgf Not ready for a PR quite yet, but here's the list I have so far for updates needed to the seed file: 
[Seed update commit](https://github.com/KaraAJC/ReadyResponder/blob/development/db/seeds.rb)

**Comment by kgf** [comment]
@KaraAJC Even if you don't have time to implement all that, feel free to open a PR, as just the research you've already done is helpful. Then, if time allows, you could complete just one, and open a PR, complete another, open a PR....
Small steps are great !

**Comment by kgf** [comment]
@KaraAJC Howdy. Could you please create a PR for the seeds.rb file? We'd love to have all the info you gathered that's in your fork.
Thanks !
Kevin

**Comment by kgf** [comment]
Thanks for your help @KaraAJC .
