### ISSUE TITLE
Inventory column titles do not scroll

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#118]
Please have inventory column titles freeze, so that the designations are readable when scrolling down the list.

**Comment by kgf** [comment]
This will probably require this change to the jQuery Datatables
https://datatables.net/extensions/fixedheader/

**Comment by kgf** [comment]
While the column headers do not freeze, there is now pagination, which should help.

**Comment by david135** [comment]
They freeze for me.  If they don't for you, there is something to investigate.  This should be a feature of all the datatables, set in `datatables-defaults.js`:
`scrollY: '50vh'`
![scrolling table](https://cloud.githubusercontent.com/assets/8586431/18771423/aee2b0b6-810c-11e6-98f2-fc382bacfa79.gif)
