### ISSUE TITLE
Dropdown menus don't work in iOS

### ISSUE THREAD

**Issue by david135** [ReadyResponder/ReadyResponder#124]
I've found a temporary solution that works for iOS, which works if placed in app/assets/bootstrap232_dropdown_menu_fix.js:

```
// This fix is for Bootstrap 2.3.2 on iOS to get the dropdown menus working.
// http://stackoverflow.com/questions/17178606/bootstrap-v2-dropdown-navigation-not-working-on-mobile-browsers
  jQuery(document).ready(function($) {
    $("li.dropdown a").click(function(e){
      $(this).next('ul.dropdown-menu').css("display", "block");
      e.stopPropagation();
    });
  });
```

I have no idea whether this fouls anything up for Android.

It seems, though, that the better solution will be to upgrade Bootstrap. Would we want something like this for now?

**Comment by kgf** [comment]
I would prefer to fix it dead, rather than a hack.

**Comment by david135** [comment]
I'm working on seeing if Bootstrap 3 fixes this.

**Comment by david135** [comment]
This seems to be resolved.  Please report if problems arise.
