### ISSUE TITLE
broken simple_forms

### ISSUE THREAD

**Issue by david135** [ReadyResponder/ReadyResponder#125]
It seems that something in the app no longer works with simple_form 3.3.0 (released today). This may be a sign that now that we're stable on 4.2.7 we should review which gems in the Gemfile now need more specific version numbers (which were removed while updating).
Changing it to `gem 'simple_form', '~> 3.2.1'` has the tests passing for me again.

**Comment by david135** [comment]
Fixed in simple_form 3.3.1, which solves the immediate problem.

**Comment by kgf** [comment]
The action on this then is to specify the version of simple_forms in the Gemfile.

**Comment by kgf** [comment]
No longer needed, the unspecified version is now 3.3.1.

A later issue may request adding specific versions to the Gemfile.
