### ISSUE TITLE
Pending Migrations for test

### ISSUE THREAD

**Issue by david135** [ReadyResponder/ReadyResponder#126]
In Rails 4.2, we can now use:
`ActiveRecord::Migration.check_pending!` or `ActiveRecord::Migration.maintain_test_schema!` to avoid issues with forgotten migrations (either by raising an exception or by keeping the test schema in sync with the development schema, respectively). [RSpec](https://www.relishapp.com/rspec/rspec-rails/docs/upgrade#pending-migration-checks) seems to recommend using the latter in `rails_helper.rb`.

**Comment by ChanChar** [comment]
@david135 I'll tackle this one. Do we want to force contributors maintain the test DB by failing if they haven't run the migrations yet?

**Comment by david135** [comment]
Thanks, @ChanChar! I'm inclined to go with the default recommendations from [RSpec](https://relishapp.com/rspec/rspec-rails/docs/upgrade#pending-migration-checks) for our version of Rails.  I don't think we need to opt out of the pending migration check, unless @kgf thinks otherwise.  I'm looking forward to benefiting from this feature when our next model comes in.

**Comment by kgf** [comment]
Sounds good to me. Thanks for your help!

**Comment by david135** [comment]
Thanks,  @ChanChar! It's merged and ready for use.

**Comment by ChanChar** [comment]
@david135 any time :] thanks!
