### ISSUE TITLE
Change log under Help looses navigation top bar

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#127]
Navigation top bar has last choice "Help", under that is "Changelog" 
If Changelog is chosen, it shows the Changelog but looses the top navigation bar.
Users who wander there looking for help are likely to need more help than when they started.

**Comment by david135** [comment]
I'd noticed that too.  I recommend, however, that we remove the Changelog.md link entirely, since it's really of use only to developers (and isn't being kept up to date).  I think it would be good to have a help page for users, though, which would use the standard template with menus.

**Comment by VanAuken** [comment]
I agree that a real help page is needed.  I'm just worried for some of our beta testers who get frustrated easily.  The help page may be awhile, the bug is now. I didn't want to get greedy!

**Comment by kgf** [comment]
This had been greatly improved by PR 129, but it still needs help. Kim is working on some content to link to.
Also, I'll open another issue describing ui changes that will allow context sensitive help.

**Comment by kgf** [comment]
This is resolved, although more attention around the help system would be good.
