### ISSUE TITLE
Privacy issue: stored uploads

### ISSUE THREAD

**Issue by david135** [ReadyResponder/ReadyResponder#128]
Without getting into the question of where to store the images (locally or through a service), perhaps we should have authorization for viewing the images, rather than simply storing them in /public.  While pictures of items may be safe (one could debate that), portraits and certifications are personal information, and we may not want to make them publicly available.

**Comment by kgf** [comment]
I do not want anything accessible without a login and a role.

@david135 Could you please provide an example URL that would retrieve an image ? Thanks

**Comment by david135** [comment]
For `items`, if the file `public/uploads/item/item_image/3/14081905676_522ed8f068_n.jpg` exists, then the URL `localhost:3000/uploads/item/item_image/3/14081905676_522ed8f068_n.jpg` displays the image, whether or not I am logged in.
For `people`, if the file `public/uploads/person/portrait/4/buddy31.jpg` exists, then the URL `localhost:3000/uploads/person/portrait/4/buddy31.jpg` displays the image, whether or not I am logged in. Note that the beginning part of the URL is pretty predictable.

From the [CarrierWave wiki](https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-secure-upload):

> Uploading files to their default directory in the Public folder can be dangerous if you're looking to restrict who can download the file. You will need to avoid uploading files to this Public directory at all costs. Instead, you can ...

At that point, we can the authorize in the way we do elsewhere (show images through a controller, authorize, etc.).

**Comment by kgf** [comment]
It looks like we could add this to the uploader config file
`config.root = Rails.root`
It may need the entire scoping

```
CarrierWave.configure do |config|
  config.root = Rails.root
end
```

That will give us the `uploads` directory.

**Comment by Spandana-Sai** [comment]
work in progress

**Comment by kgf** [comment]
Excellent, thanks!

**Comment by kgf** [comment]
I am mentioning this on all the claimed issues. We always appreciate people's help, but if you could have any PRs submitted by 1PM EST this Sunday, I'll have time to review and integrate them for a scheduled demo on Monday.

Thanks !
Kevin

**Comment by Spandana-Sai** [comment]
Hey PR has been submitted #247 Please Review. Sorry for the delay.

**Comment by kgf** [comment]
No problem, thanks for your help! Iwilli review this after the demonstration later today.
