### ISSUE TITLE
Change Items View to better reflect reality

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#133]
We'll need to change the item view. We should remove the `serial X` columns, as they don't really apply anymore. Also, I'd like to remove the `Available` status column, and just colorize the row itself. The concern I have is if it's printed on a b/w printer, that info would be lost. 
https://datatables.net//forums/discussion/34882

**Comment by david135** [comment]
Table columns removed in PR #146, but will we want to remove these fields from the db?

**Comment by kgf** [comment]
Yes, a migration should be created to remove these fields.

**Comment by david135** [comment]
Resolved with #185.
