### ISSUE TITLE
The term "LIMS" should be removed from the UI

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#135]
Especially in app/views/layouts/_top_menu.html.erb, where it can be replaced by "Home"

Long term this should be a configurable thing, but for now...

**Comment by neeleshn** [comment]
Hey,

I am a first-timer. Can I claim this?

Thanks,
Neel.

**Comment by kgf** [comment]
Absolutely ! You know about the free T-shirt ?
https://hacktoberfest.digitalocean.com/

Let me know if you need any help.

Thanks !

**Comment by kgf** [comment]
Thanks @neeleshn for looking at this. Is there another issue we could interest you in ?
Thanks @pcofilada for the pull request !
