### ISSUE TITLE
Making sure dates are in the correct order

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#140]
On several forms, we enter start and end times. There should be validations on all these models to require that `end_time` is after `start_time`.  What would be much better would be to have validations in the form, using Javascript, to catch these errors before they get to the backend.

The ideal PR would verify that all models have validations, that there is JS to help the user before form submission, and tests to test it !

**Comment by david135** [comment]
I've got the validations and tests taken care of in my next PR. I don't yet have a plan for JS.

**Comment by kgf** [comment]
I would accept that PR, and make a new issue for the JS.

**Comment by david135** [comment]
PR #146 should help with this.
