### ISSUE TITLE
Expired certs still grant the skill

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#15]
Expired certs should still be shown, but they should not grant the skill.

**Comment by kgf** [comment]
This would be good to have !

**Comment by cesc1989** [comment]
@kgf would you mind explaining a bit more about this to me? I still struggle to understand some terminology specific to this project.

Thanks! :)

**Comment by kgf** [comment]
@cesc1989 Thanks for your interest. As a preamble, I'm not super thrilled with the naming in this area. Others have complained. Naming is hard. I'm open to suggestions.
People get certifications, such as a driver's license. They get the certification in a particular Course, such as `PR driver's license` which specifies the term of the certification, etc. This gives them a skill, such as `Standard Driving`. This skill may be a requirement of a title, such as CERT member. 
The issue is that once the certification is expired, it should no longer count towards having that skill. It should still be shown, but it no longer counts.

Hope all that helped. Other questions ?

**Comment by cesc1989** [comment]
Thanks @kgf I'll give it a deeper look and see whether I could work on this. I'll let you know.

**Comment by kgf** [comment]
@cesc1989 Did you have any further questions ? Any updates ?

**Comment by cesc1989** [comment]
Not right now. I'm working my way through the app and I'll let you know. Thanks for asking! @kgf

**Comment by kgf** [comment]
Ok, thanks for your help.
