### ISSUE TITLE
Datepicker changes values by accident

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#151]
When using a Mac, you can scroll on a page by using two fingers on the touchpad and sliding them up or down. If the mouse cursor is inline with a field that includes a datetimepicker, the mouse becomes "caught", and scrolling further will cause the value in that field to change. This is very unexpected, and bad. I believe this could be fixed by only having the datetime picker be activated on the click event.

Go to this documentation page ==> http://xdsoft.net/jqplugins/datetimepicker/
See this section for an example  =>  `handler onclick event`

**Comment by david135** [comment]
Does PR #150 work for you? I was able to replicate, and the configurations I installed seem to fix it for me.

**Comment by david135** [comment]
PR #150 has been merged.
