### ISSUE TITLE
Tasks will need new statuses.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#154]
Tasks currently have status choices of Full, Partially-full and Empty. These will need to change to something like Empty, Inadequate, Adequate, Satisfied, Full to reflect the lower Requirements model. 

Empty means no one has been assigned to anything. All requirements are empty.
Inadequate means there are still requirements that have not met their minimum staffing levels.
Adequate means all tasks have met their minimum staffing requirements.
Satisfied means all requirements have met their desired staffing levels.
Full means all requirements have met their maximum staffing levels.

This means requirements will need these supporting fields, minimum, desired and maximum.

**Comment by kgf** [comment]
@david135 I think you closed this as part of requirements, right ?

**Comment by david135** [comment]
Correct, though until we have assignments, they are stubbed, and not fully-functional.
