### ISSUE TITLE
Have person form look to the department for division choices.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#161]
This is a continuation of #145. The person form should use the values from the department that the person belongs to drive the choices on the person form.

So, if I have a department of MRC with division1 choices of "Medical Team 1", "Medical Team 2" and division2 choices of "Doctors", "Nurses", then those should be the only choices in the select field of the form. If I change the department, these choices should go away, and new choices should appear.

**Comment by avinoth** [comment]
I could do this after #187 is confirmed?

**Comment by kgf** [comment]
@avinoth Would you still be willing to handle this one ? There is code on the location that might be helpful.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/items/_form.html.erb#L6

**Comment by avinoth** [comment]
@kgf I afraid not. I'm packed for the upcoming two weeks.

**Comment by kgf** [comment]
No problem, knowing I can give this to someone else is helpful. Perhaps when that's over. 

Thanks for your interest.
Kevin

**Comment by kgf** [comment]
fixed by #225
