### ISSUE TITLE
Remove sqllite from Gemfile

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#163]
We are using PG in all environments

**Comment by pratyushprakash** [comment]
Hi, can I work on this issue?

**Comment by david135** [comment]
This issue has been claimed.  Thank you for your interest, but we wouldn't want you to duplicate work that's already being done.  Perhaps another issue will catch your interest?

**Comment by david135** [comment]
Resolved in #164.  Thanks for everyone's interest!
