### ISSUE TITLE
Add Recipients to Person model

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#165]
This should follow the description in the wiki.

**Comment by nickgnd** [comment]
Hi, i'm wondering if @BoVice is still working on this issue, if not I'd like to work on this.
Let me know 😄

**Comment by kgf** [comment]
I have not heard from @BoVice recently. @nickgnd have you looked at the project, are there other issues that would interest you ?
https://github.com/ReadyResponder/ReadyResponder/projects/1

**Comment by kgf** [comment]
@BoVice :
I am mentioning this on all the claimed issues. We always appreciate people's help, but if you could have PRs submitted by 1PM EST this Sunday, I'll have time to review and integrate them for a scheduled demo on Monday.

Thanks !
Kevin

**Comment by abrophy** [comment]
#198 needs the recipient model in order to link to person, according to the wiki
