### ISSUE TITLE
New Person form: 'Create New Person' should go to view of people

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#170]
In New Person form, when the data entry is complete and the button is hit for 'Create New Person', currently it goes to the home page.
The program should go to a view showing that the person was created.  This gives the data entry person confirmation that they sucessfully entered the new person.  Appropriate view might be 'Everybody'.

**Comment by kgf** [comment]
Would this be to show the individual person you just entered, or a listing of many people ? If a listing of people, would it be better to show a listing of just the people in the department that is the same as the new person's department ?

**Comment by david135** [comment]
I'll take this one.  It's ultimately related to #123, though we'll want to discuss a solution for the entire site.

**Comment by kgf** [comment]
@david135 Should we re-add the awaiting info tag so @VanAuken can answer the question I posed ? She is an end user, and how _she_ thinks it should work is important.

**Comment by david135** [comment]
Yes indeed. Thanks!

**Comment by david135** [comment]
This is handled in #197.  I'll leave this issue open for a few days in case anyone wants to make further suggestions, and then close it.
