### ISSUE TITLE
Code of Conduct needs contact information

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#171]
In the Code of Conduct referenced in README,  contact information needs to be inserted in document.  Currently reads:

"contacting a project maintainer at [INSERT EMAIL ADDRESS]."

**Comment by kgf** [comment]
That email address should be `conduct@readyresponder.org`.
That address is not yet hooked up. In fact the readyresponder domain is not properly configured, but this will be a step in the correct direction.

**Comment by ankit01ojha** [comment]
Is the project is removed from hacktoberfest?

**Comment by david135** [comment]
Hi @ankit01ojha, thanks for your interest!  This project is still taking part in Hacktoberfest, but this particular issue had been claimed already, and in fact has now been resolved with PR #177.

**Comment by kgf** [comment]
Hi @ankit01ojha, thanks for your interest! We do still have Hacktoberfest issues available, if we can tempt you....

Kevin
