### ISSUE TITLE
Create Conversations, link to Recipients

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#186]
A conversation is the result of a single notification. It is an discussion between the system and a single person, using a single method of communication

It will have many messages.
 You should refer to the wiki for further details
https://github.com/ReadyResponder/ReadyResponder/wiki/Notifications

**Comment by nickgnd** [comment]
I'm on it!

**Comment by kgf** [comment]
That's great. When do you think you might have a PR ?

Thanks for your help !

**Comment by kgf** [comment]
The #show action for any conversation should have a link back to the recipient and the notification. It should also have a datatable showing all the messages in chronological order, and color coded by direction (Inbound vs outbound) You can look at the event show page ERB for examples of a lot of that...

**Comment by nickgnd** [comment]
Hi @kgf, i'm sorry, i was very busy in these past days. I hope to take a look in this weekend and send to you a WIP PR.

**Comment by kgf** [comment]
That would be great, especially if you could have it in by 1:00 PM Eastern Time. That will give me some time to review and integrate the changes for a demo I'll be giving on Monday.

**Comment by kgf** [comment]
@nickgnd This issue is being closed, as we do not need this model. I am updating the wiki with the details.
I hope you see this in time !

**Comment by nickgnd** [comment]
@kgf ok! In the meanwhile I set up Docker for the development environment. It could be useful to the project?

**Comment by kgf** [comment]
Probably not, as not too many use Docker on development yet. I think improvements to the seeds.rb would probably be of more value to new contributers. ( #110 and #22 )
That being said, I would certainly approve a PR with a Dockerfile !!

@nickgnd Are you up for a different issue ? #212 perhaps ?

Thanks for your help !
Kevin
