### ISSUE TITLE
Create messages model, link to person.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#198]
See https://github.com/ReadyResponder/ReadyResponder/wiki/Notifications

The ideal PR would include tests for this model.

**Comment by nickgnd** [comment]
Hi @kgf, I'm on it 😄 

Before to start, can you please give me more info about the requirements? Thanks.

step by step:

**create model `messages`**
I saw there is already a table `messages` in the [db schema](https://github.com/ReadyResponder/ReadyResponder/blob/development/db/schema.rb#L227) with different fields from those listed in the [wiki](https://github.com/ReadyResponder/ReadyResponder/wiki/Notifications). How do I proceed?
- I keep the currents fields in the table and add those specified in the wiki

or
- I keep only the fields specified in the wiki and delete the others

Do you want some data check at db layer?  For example null check? 
Do you need extra indexes on specific fields? For example `status` or `sid` ?

**`belongs_to conversation`**
Do you want add a foreign key on `conversation_id`?

**message_time**
Do you want to save the message datetime in a specific time zone?

**message => string**
String or Text?

Thanks, and feel free to give me others suggestions.

**Comment by kgf** [comment]
Thanks a lot for your help !
I do have a slight concern with you choosing this one, as it is tied to #186, which is not yet claimed. Do you see this as a problem for you ?

The current messages table can be deleted, or changed to your desire. There is no data in it in production. So that would be the second option.
Null checks are usually good !

All times throughout the app should be stored in UTC, and then displayed in local time.

> Do you want add a foreign key on conversation_id? 
> Yes, to support the `belongs_to`

The `message` class should have a method for channel, probably defined as `message.conversation.channel`.
It should have similar method for `recipient`

Thanks for your interest. Let me know if you have other questions.

**Comment by nickgnd** [comment]
Hi @kgf, 

> I do have a slight concern with you choosing this one, as it is tied to #186, which is not yet claimed. Do you see this as a problem for you ?

Of course not 😄 . I'll work on #186 in the next days then I can  proceed with this one.

Thanks for the feedback!

**Comment by kgf** [comment]
That's great Nicolò. Just be sure to check back in before beginning on #198. I have a demo coming up on Monday of next week, and I am hoping to have more of the Event project done, so others may take the other ticket.
Thanks for your help !

**Comment by kgf** [comment]
I am mentioning this on all the claimed issues. We always appreciate people's help, but if you could have PRs submitted by 1PM EST this Sunday, I'll have time to review and integrate them for a scheduled demo on Monday.

Thanks !
Kevin

**Comment by kgf** [comment]
I realized I can still work on the text message portion of this, but will need the messages model before Sunday afternoon

**Comment by abrophy** [comment]
Don't want to step on any toes, seeing as this issue's already been claimed, but with other issues relying on the model how do you feel about someone else putting in a PR for this?

**Comment by kgf** [comment]
I appreciate your considering others. I think @nickgnd may have gotten busy. I have made some good progress on the text messages, and would welcome a pr for the model. Thanks for your interest!

**Comment by nickgnd** [comment]
Yeah @kgf, now I'm a little busy. @abrophy feel free to contribute :)

**Comment by kgf** [comment]
We hope to see you again on the other side. Thanks for the update, @nickgnd

**Comment by kgf** [comment]
@abrophy  any questions ? any progress ? Perhaps an interim PR ?

Thanks for your help.
Kevin

**Comment by abrophy** [comment]
Sorry got distracted with that service object, will slam this out real quick

**Comment by abrophy** [comment]
#266 is the other half of this relationship, according to the wiki it serves as the linking table between messages, persons, and notifications
