### ISSUE TITLE
Add tabs to events UI

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#202]
I would like to add tabs to the events UI to separate personnel tables from the tasks info.
This should use the jquery library

**Comment by chirag08** [comment]
Can you describe a bit more ?

**Comment by kgf** [comment]
Sure, thanks for your interest. Looking at this screenshot:
![screen shot 2016-10-17 at 12 47 58 pm](https://cloud.githubusercontent.com/assets/2431417/19446707/04a3286e-9468-11e6-84cf-053eecc796a9.png)
You can see a `Tasks` table, an `Availabilities` table and an `Unknown` table. There may be additional tables in the future. `Availabilities` and `Unknown` are about who is responding. This should be on one tab, perhaps entitled People. `Tasks` is about what those people are doing, and should be on it's own tab.

Does that help ? @chirag08

**Comment by kgf** [comment]
What do you think, @chirag08 ? Are you up for it?

**Comment by david135** [comment]
http://getbootstrap.com/javascript/#tabs ?

**Comment by kgf** [comment]
Well, I must admit I had been thinking
https://jqueryui.com/tabs/

**Comment by colinfike** [comment]
I'll take this one if it's still available. 

Just to confirm, the task is to use jQuery UI Tabs and make two tabs. One for Availability and Unknown and another for Tasks.

**Comment by kgf** [comment]
That is correct, unless you are aware of a reason to use a different library. JavaScript is not one of my better subjects!
Thanks @colinfike !
