### ISSUE TITLE
Department needs to know to track people and items

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#209]
The department needs two boolean attributes, `We track people for this department` and `We track items for this department`. Checkboxes on the UI should be good. 

These will be used to drive UI choices.

**Comment by chainedcoder** [comment]
Lemmi try

**Comment by chainedcoder** [comment]
Hey @kgf, To what file is this supposed to be added?

**Comment by kgf** [comment]
You would need to take a few small steps. You would need to generate a migration to add the two columns to the database. They could be `manage_people` and `manage_items`. You would need to add the two fields to the department form. You would need to update the model to make these be whitelisted attributes. And you might write a test to ensure they could be selected. There may be other steps, but that would be a good start.

Does that help, @stevenkayter ?

**Comment by kgf** [comment]
I am mentioning this on all the claimed issues. We always appreciate people's help, but if you could have PRs submitted by 1PM EST this Sunday, I'll have time to review and integrate them for a demo scheduled on Monday.

Thanks !
Kevin
