### ISSUE TITLE
Change events listing to show partial availability

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#212]
Looking at this recent screenshot, we see that one person is available, and two have not responded. No one has reported unavailable yet. There are three small numbers at the top, outlined in green red and yellow. They currently mean Available, Unavailable, and Unknown. This issue looks to change that. The desired display is to have four numbers. A green background still means available, _then_ a yellow background, which means they're available for _part_ of the event; partially available. Then a red background which, like now, means they are unavailable. Finally, a number with a grey background, showing the number of people who have not responded. This would also want the styling of the `No Responses` table to be no background, and the Available table to have styling showing yellow for the folks partially available. That should probably make a call to the `Event` class to determine partial availability. Also, the size of these number squares should be increased to make it easier to see on a mobile client. These numbers are very important,

![screenshot](https://cloud.githubusercontent.com/assets/8333278/19616743/595de572-97e9-11e6-94d0-81a9db048afb.png)

_New Improved Version:_
<img width="1190" alt="screen shot 2016-10-22 at 11 00 43 am" src="https://cloud.githubusercontent.com/assets/2431417/19620237/dfa399da-9846-11e6-81c3-2a59357f2110.png">

**Comment by kgf** [comment]
The ideal PR would be ready by 1PM EST tomorrow, so I could include it in a demo on Monday.

**Comment by kgf** [comment]
This is the bit in the class that will need a new method
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L34-L48

**Comment by colinfike** [comment]
taking a look now

**Comment by kgf** [comment]
Thanks for your help!

**Comment by colinfike** [comment]
No problem, happy to help

**Comment by kgf** [comment]
Closed by #220
