### ISSUE TITLE
Add Horizontal sub menu site wide for contextural actions/buttons

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#214]
Add Horizontal sub menu site, wide for contextural actions/buttons.
Goal is to have contextural buttons, like 'add new person' on Applicant view.
Views could then move over to left hand edge and allow more columns.  Currently left hand 'gutter' is left open for buttons.

**Comment by kgf** [comment]
I'm going to close this for now. There are many other UI areas that are of higher priority, and the current blue actions flow nicely on a cell phone.
