### ISSUE TITLE
Create a seeds.rb file to pre-populate database

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#22]
An example of the data would be setting up an initial user to allow logins.

**Comment by kgf** [comment]
There is overlap between this and #107

**Comment by andrew-schutt** [comment]
Hello @kgf this pull request still need some work?  I see that you referenced an closed a couple other associated issues with this one?  Just wanted to double check before trying to start work on this issue.  Thanks!

**Comment by kgf** [comment]
Yes, I believe it still needs help. It does not create an enough tasks requirements notifications for example. 

Thanks for your interest

**Comment by kgf** [comment]
I'm going to close this, as it's too vague. I will create additional issues for specific missing models.
