### ISSUE TITLE
Make top menu dynamic for people

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#231]
Right now, the People menu drops down to reveal sub menus. The first two choices are currently static. They should be changed to reflect the Active departments that have the `We manage People` setting set to true. You should use `shortname` attribute for display in the menu. This will also require changes in the people controller, since the values are also hard-coded there.

**Comment by sergeimellow** [comment]
taking a look at this now

**Comment by kgf** [comment]
Awesome, let me know if you have questions !

**Comment by sergeimellow** [comment]
@kgf Is there a reason that the relationships aren't established between departments and people? Person.first.department just returns a string instead of the department the user is related to.

**Comment by kgf** [comment]
Almost certainly an oversite from a time when Departments weren't a model. At this point, that would be a bug !

**Comment by sergeimellow** [comment]
@kgf This will help the next person who tries to tackle the initial problem whether its me or somebody else. I am done for now.

https://github.com/ReadyResponder/ReadyResponder/pull/242/files

**Comment by kgf** [comment]
Thanks for your help ! I appreciate it.

**Comment by kgf** [comment]
Resolved in #298
