### ISSUE TITLE
No way to enter a new skill

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#237]
When you go to the skills listing, please add a "New Skill" button to the left hand margin. In this screen shot, "New Task" is an example.

<img width="517" alt="screen shot 2016-10-23 at 6 05 21 pm" src="https://cloud.githubusercontent.com/assets/2431417/19629832/616e8998-994b-11e6-8332-072f0d69b678.png">

**Comment by maisieccino** [comment]
I'm happy to give this a go! :smile:

**Comment by kgf** [comment]
Great, thanks for your help!

**Comment by kgf** [comment]
Btw, there was a similar issue recently that has a closed PR. You may want to take a look.
