### ISSUE TITLE
No way to enter a new title

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#238]
When you go to the titles listing, please add a "New Title" button to the left hand margin. In this screen shot, "New Task" is an example.

<img width="517" alt="screen shot 2016-10-23 at 6 05 21 pm" src="https://cloud.githubusercontent.com/assets/2431417/19629841/7f73fd7e-994b-11e6-9a8e-2f2b34957163.png">

**Comment by Spandana-Sai** [comment]
@kgf If only one sidebar is there in title listing then instead of left margin we can go with the design approach of Resource listing? What is your opinion? and one more thing there is no ability defined for title

**Comment by kgf** [comment]
Your current pr addresses this issue, so intend to merge it. Perhaps a different pr for adding title to ability?

Thanks for your help.
