### ISSUE TITLE
When entering an availability, exact same time shows as partially available.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#239]
An event has a start time and an end time. If you enter an availability with those exact times, you are listed as `partially available`, not `available`. 
We do not need seconds in these times. A later issue will try to normalize all times to quarter hours.
As you can see from the screen shot, the event is from 7 until 9. Abigal is available during those times, but is only shown as partially available.
The ideal PR would include a test that would expose the bug.

<img width="900" alt="screen shot 2016-10-23 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/2431417/19629981/9d51506e-994e-11e6-8c45-70e3e4bf5a1f.png">

**Comment by EvanTedesco** [comment]
I have made a pr for this here: https://github.com/ReadyResponder/ReadyResponder/pull/245
