### ISSUE TITLE
When editing a Person, cancel doesn't work

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#243]
When you edit a person, the cancel button seems to just come back to edit.

**Comment by EvanTedesco** [comment]
Where do you want it to go?

**Comment by kgf** [comment]
Back from whence you came. I believe @david135 worked on that recently, #210 
Were you able to duplicate ?

**Comment by EvanTedesco** [comment]
It brings me back to the user's show page when I press it.

**Comment by kgf** [comment]
OK, let me try it again, get better details.

**Comment by abhishekbose87** [comment]
The `Cancel` button works for me. It takes me back to the index page.

@kgf Were you able to replicate the issue ?

**Comment by kgf** [comment]
I have not had time to test. Working hard on the texting integration. If it's working for you, I'll close this and re-issue if needed. Thanks for checking !

Kevin
