### ISSUE TITLE
When looking at event availability, links should be consistient

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#244]
When looking at an event, as shown in the screen shot below, you will have some people who have responded, and some who have not. In both these tables, the person's name is a link. What's confusing is that they are links to different things !  The name should always be a link to the person. For the table of responses, the badge in the first column should be a link to the Availability record itself.
Thanks

<img width="414" alt="screen shot 2016-10-23 at 8 46 15 pm" src="https://cloud.githubusercontent.com/assets/2431417/19630931/58a968e8-9962-11e6-954a-bb5c4f25d61e.png">

**Comment by EvanTedesco** [comment]
Can you elaborate a bit?  Perhaps git it in terms of a user story.  What is the current behavior and what is the desired behavior?

**Comment by kgf** [comment]
When a user is looking at availabilities tab on an event, and clicks on a person's name that is a link, the link should go to the record for that person. Currently it does go to the person record if that person is in the unresponsive table. (The lower one) 

If they are in the Availabilities table (the upper one) it goes to the availability record. This link should be changed. A second change is to make the first column of the upper table, the badge, be a link to the availability.

So all changes are to the upper table
Does that help ?

**Comment by abrophy** [comment]
I can see the issue, will send a PR shortly
