### ISSUE TITLE
Create a service object to adjust times.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#259]
Given a start time and an end time, it should adjust them.
It should first remove the seconds and microseconds so we don't move times falsely.
It should adjust the start time to the nearest quarter hour after the the time given.
It should adjust the end time to the nearest quarter hour before the the time given.
If either time is already on the quarter hour, it should do nothing.
All times returned should not have a seconds or micro-seconds component, minute is specific enough.
This service should accept an object, such as event or availability. It should not care what type of object, only that it has those attributes.

_Please_ include tests.

Thanks for your help !

**Comment by abrophy** [comment]
I'd like to give this a go :raised_hand:

**Comment by kgf** [comment]
That would be great, thanks for your help !
Let us know if you have any questions.

Kevin
