### ISSUE TITLE
Make first user an admin

### ISSUE THREAD

**Issue by houhoulis** [ReadyResponder/ReadyResponder#26]
When someone runs the application locally, they have to go into the console to give themselves admin rights before they can do anything.

Hook into Devise so that the first user created has admin rights.

**Comment by kgf** [comment]
There is some overlap with #107

**Comment by kgf** [comment]
There is now enough code in the `seeds.rb` to create the admin user, and spit out the password.
While the seeds.rb could use additional attention, this ticket is resolved.
