### ISSUE TITLE
Create a service object that will copy all tasks and requirements from one event onto another

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#260]
This service object should take events. The template event should be expected to be persisted, with a start time and multiple tasks and requirements. The new event should have a start time. If the template task has a start time, you should calculate the delta from the template event to the template task, then apply it from the new event start time.

If you have questions, please ask.
Thanks for your help.

**Comment by abrophy** [comment]
I'd like to attempt this one as well ✋

**Comment by kgf** [comment]
Wow, sounds great ! Thanks
Kevin

**Comment by abrophy** [comment]
I'm assuming that the object should create and persist the new event along with its tasks and requirements, then return a reference to this new event.

What should the service object return if the template event isn't persisted?

**Comment by kgf** [comment]
Your first assumption is correct. 
It would be tough to get into the second situation. Until the template is persisted, it will not appear as a selection in the drop down in the new event. Feel free to throw an error.

**Comment by kgf** [comment]
@abrophy Would you still be willing to work on this ?

**Comment by kgf** [comment]
This was closed by #408
