### ISSUE TITLE
Manage notification statuses in controller 

### ISSUE THREAD

**Issue by amandamunoz** [ReadyResponder/ReadyResponder#262]
Users can only choose `Pending`, `Active`, or `Canceled`. A new Notification can only be changed to `Pending` or `Active`. A `Pending` one can only move to `Active` or `Canceled`. You could capture the state machine in a hash, using the current state as the key, and the possible transitions as the values. (Originally commented on https://github.com/ReadyResponder/ReadyResponder/pull/205)

**Comment by kgf** [comment]
Thanks for your help.

**Comment by swaathi** [comment]
I can work on this. :)

**Comment by kgf** [comment]
@swaathi thanks for your interest.
@amandamunoz has already claimed this issue, which makes sense, since she has done other work in this area. I would not want you to waste your time. Perhaps #237 or #254 could interest you ?
I hope you'll join our project.
Thanks,
Kevin

**Comment by swaathi** [comment]
Oops. That sounds smart. :) Let me see what #237 and #254 is about! :)

**Comment by kgf** [comment]
Great @swaathi . If you have any questions, feel free to ask. If you have a certain area of software development you're interested in, let me know. We probably have an issue in that area ! (Even if I haven't entered it yet...)

Thanks, 
Kevin

**Comment by swaathi** [comment]
I love optimizing stuff. If you have any module you need refactoring, I'd be glad to help. :)

_
Swaathi K
CTO, Skcript

**Comment by kgf** [comment]
I believe this has been closed by other PRs
