### ISSUE TITLE
Refactor partial availability

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#263]
This does currently work, but I suspect it is not optimal. There is currently a bug in the four small status boxes showing the incorrect value.
The ideal PR would include tests.
If an Availability start time is less than or equal to the start time of the query, and the Availability end time is equal to or greater than the end time of the query, then it is "Available", Otherwise, I think it is unavailable.
I think this should be turned into a service object. It will be needed for both tasks and events, and perhaps others. It could be passed a Person (to get all their availabilities) and another object ( perhaps a task or an event, as long as it responds to start_time and end_time )
The code currently involved is around here => 
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L36

This one's for you @swaathi !
Thanks for your help.
Kevin

**Comment by swaathi** [comment]
Thanks Kevin. Looking into this now.

**Comment by kgf** [comment]
Great, thanks for your help.

**Comment by swaathi** [comment]
When you said this,

There is currently a bug in the four small status boxes showing the incorrect value.

Do you know the scenario in which this happens? Does the seed file contain that data which causes this bug?

**Comment by kgf** [comment]
Sorry, seeds.rb does not cause the bug. It could be related to the fact that we currently allow duplicate availabilities for the same time span. You can see the issue in the attached screen shot, which shows the entire availabilities table. 
<img width="897" alt="screen shot 2016-10-28 at 9 23 14 am" src="https://cloud.githubusercontent.com/assets/2431417/19807989/9edac640-9cf0-11e6-8e88-2d34bfb13a23.png">
Thanks for your help
Kevin

**Comment by swaathi** [comment]
Awesome. This helps. Will try to fix it by Sunday. :)

_
Swaathi K
CTO, Skcript

**Comment by kgf** [comment]
Thanks for your help !

**Comment by swaathi** [comment]
No problem! I hope this addresses your bug. Feedback is welcome! :)

**Comment by kgf** [comment]
Closed, will need a better description to make it actionable.
