### ISSUE TITLE
Create a basic CRUD model for Settings

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#264]
This would include the all 7 resources. 

Add the index view link under the `Admin` nav menu.

Thanks for your help.
Kevin

**Comment by abhishekbose87** [comment]
Hi @kgf, Can I work on this issue ?

I plan to use rails scaffold to get the templates, so if there is an existing model which I could refer, I could remove unrequired stuff from scaffolding code.

**Comment by kgf** [comment]
That would be great, thanks.
If you look at the recent PR for requirements, it should have a lot of what you need. It shows examples of how to add the custom navigation buttons on the side nav.
https://github.com/ReadyResponder/ReadyResponder/pull/207

**Comment by abhishekbose87** [comment]
Can you mention the fields that will be present in the settings model ?

**Comment by kgf** [comment]
Sure, thanks for your help...
name
description
key
value
category Some way to group them.
status {Active, Inactive} Might have alternative API keys, some inactive, one active
required { Boolean } Signifs a setting which must be present for app to function properly.

They would mostly be string. Required => boolean, description => text.
If you have any other questions, please ask. Thanks for your help.
Kevin
