### ISSUE TITLE
When creating a new channel, priority is showing up as a number, not a string

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#27]

**Comment by kgf** [comment]
If you **Add a new person**, and go down to the Phone area, there is a point to add Priority. There is a drop down select which is populated with just numbers. It should have a label as well, so that you know which one to pick.

**Comment by kgf** [comment]
Values for the label would be 

1 Use First
2 Use Second
3 Use Third
4 Use Last

**Comment by kgf** [comment]
@ThomasCarlson , do you still have your fork for this issue ?

**Comment by caironoleto** [comment]
I'm working on this issue.
