### ISSUE TITLE
Add comments as a distinct model to Person

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#272]
I am scoping this to only person to make multiple small issues.
Comments will be used on many models, such as items, tasks, pretty much everything. Most things will be `commentable`. I think it would be good if this was implemented as a Rails concern, so it could be easily added to additional models going forward. I am open to suggestions in that regard. There should be a table at the bottom of person showing all comments, most recent at the top. That enough for this issue.

https://richonrails.com/articles/rails-4-code-concerns-in-active-record-models

**Comment by abhishekbose87** [comment]
I would like to take a jab at this one.

**Comment by kgf** [comment]
Excellent, thanks for your help.
Kevin

**Comment by kgf** [comment]
@abhishekbose87 did you have any success? Do you have questions?

**Comment by kgf** [comment]
This work has been started, as can be seen here.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/comment.rb

**Comment by alexshook** [comment]
@kgf hey do you still need someone to do this?

**Comment by kgf** [comment]
Absolutely, @alexshook that would be great. Thanks !

Any questions ?

**Comment by alexshook** [comment]
Not right now, @kgf, but will let you know if I think of any. Thanks!

**Comment by kgf** [comment]
@alexshook Any updates ? Are you stuck on anything ?

**Comment by alexshook** [comment]
@kgf I have a branch with changes that I'd like your feedback on before proceeding with any further. Has become a busy day so I'll open a PR for you with some questions tomorrow.

**Comment by kgf** [comment]
@alexshook That's great ! I look forward to seeing the PR tomorrow.

**Comment by kgf** [comment]
Closed by #565 , although a follow-up issue will be needed to create the comments.
