### ISSUE TITLE
TimeRounding service does not handle the last quarter hour correctly

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#274]
This line has an issue when the minutes are between 45 and 59.
The PR addressing this should include tests for this code.
The correct level of testing would be 4 contexts, one for each quarter of the hour, each with an assertion for the start time and an assertion for the end time.

Also see #265 

https://github.com/ReadyResponder/ReadyResponder/blob/development/services/time_rounding_service.rb#L23

**Comment by abrophy** [comment]
I'll claim this one, as it was me who introduced the bug, if you don't mind

**Comment by kgf** [comment]
Great, thanks for your help.
