### ISSUE TITLE
Add data table to Events for Notifications

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#275]
On the event show page, there are currently two tabs. This would be to add an additional tab. The tab should have a data table showing notifications for this event. You should use the same JS code used for the Availability listing on one of the other tabs.

**Comment by jeffhos** [comment]
I'll work on this.

Question: I noticed there's a line in the `notifications#index` table that says "I need to allow info only Notifications".  Should that be converted to a `TODO`-type comment (or filed as an issue), or is it something that needs to remain in the template?

**Comment by kgf** [comment]
A Todo style comment would be good.
Thanked for your help!
Kevin
