### ISSUE TITLE
Add additional attributes to Notification

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#282]
The wiki details what should be there. Subject missing is a biggy, that's the message to send out !
https://github.com/ReadyResponder/ReadyResponder/wiki/Notifications

Thanks
Kevin

**Comment by romangurovich** [comment]
I can take this one.

Adding these fields:
- subject:string
- body:text

Need clarification on the following:
- departments and divisions (serialize or join table ?) ( Future iteration )
  >>> _is this a has-many association? do we want to implement it now?_
- groups => Available, Unavailable, Unknown, (Assigned, in the future)
  >>> _is this a has-many association or just a string limited to 'available', 'unavailable', 'unknown'?_
- channels => E-mail, Voice, Text
  >>> _is this a has-many association or just a string limited to 'email', 'voice', 'text'?_

If groups and channels are strings, should we store them as lowercase, and determine how they're displayed elsewhere (either in a presenter, or preferably in an en.yml locale)?

For example we can store `email` and display appropriate verbiage for the region: `E-Mail` for an English locale, and `Эл. адрес` for a Russian one

**Comment by kgf** [comment]
@romangurovich it appears you have some knowledge around i18n ? If so, I am quite interested in your help. It has been on my radar, especially as I saw the folks putting in pull requests from around the world. 
The departments can be a join. The divisions will be a bit tougher, we can leave that for a future effort. Divisions are a subset of a department. 
Groups should store the string, it looks to Availability for the information on Available, Unavailable and Unknown.
Channels are just a serialized string.
If you want to just focus on internationalizing channels, that would give a reference design that I can point others towards, that would be fine.

Thanks for your help,
Kevin

**Comment by romangurovich** [comment]
https://github.com/ReadyResponder/ReadyResponder/pull/287
