### ISSUE TITLE
Move action buttons to sidebar

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#290]
All actions should be in the sidebar, rather than at the bottom.

In this file 
app/views/settings/show.html.erb
and this
app/views/settings/new.html.erb

And anywhere else for settings

**Comment by anncolvin** [comment]
I'd love to take this one!

**Comment by david135** [comment]
Great!  Thanks for taking this on, @anncolvin.

**Comment by kgf** [comment]
Yes, thanks @anncolvin . Let us know if you have any questions.

**Comment by kgf** [comment]
@anncolvin Are you having any success ? Do you have questions ?

**Comment by anncolvin** [comment]
I just submitted a pull request. Please let me know if there are any issues with it.

**Comment by kgf** [comment]
Closed by #302 
Thanks for your help @anncolvin
