### ISSUE TITLE
Make the Org Chart menu choices dynamic

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#293]
The menu choices should be `All the departments that are active, and that have managing people true`
Obviously, this will require changes in the people_controller as well.

**Comment by pcai** [comment]
I'm happy to take a shot at this if it's still up for grabs.

**Comment by kgf** [comment]
It is, thanks. I'll try to update the ticket with better details.

**Comment by kgf** [comment]
If you look at how the `People` menu is implemented, this may be similar. 
Right now, when you request an orgchart, it only shows one department. It would be better if there were a sub-menu, and you could select which department. If you created a new department, AND selected that it managed people, then that new department would begin appearing as a choice for the orgchart.

The orgchart itself should show each group of `division1` values as a section.

**Comment by pcai** [comment]
Thanks @kgf - I didn't realize the referenced menu didn't exist yet. That sounds straightforward enough though. I opened PRs for a few fixes that were blocking me, will revisit this once those are merged.

**Comment by kgf** [comment]
@pcai Does this still interest you ? Hacktoberfest is coming, I'm sure you need a new t-shirt !

**Comment by pcai** [comment]
Sorry for the (long) delay. I opened a preliminary PR to check if I'm on the right path? Please see attached screenshots in 462.
