### ISSUE TITLE
Validation needed on ID code when creating event

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#300]
On form for New Event, the (user/entry personnel) can enter the ID code, however the code should be unique.
Validation is needed to warn / restrict (user/entry personnel) from entering a code that has already been used.
Duplication of a code could result in signing the (end user/volunteer) up for whichever event was first returned by active record rather than the event intended by the (end user/volunteer).

**Comment by kgf** [comment]
A few more details. Both Events and Notifications have `id_codes`. The validation would need to check both for duplicates. Also, this validation will also be needed on Notifications. Also, an id_code can be recycled once the event/notification is cancelled/complete/closed. Event then, to prevent confusion, they should probably wait six months or so before being valid again.

**Comment by kgf** [comment]
Also, this line should be updated to only look at scheduled or in-session events
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L85

**Comment by kgf** [comment]
I'm going to close this, as it had been completed. I'll open a new ticket just for notifications
