### ISSUE TITLE
Event#upcoming should not show events from the past

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#304]
Currently, this line does not filter out events from the past, instead relying on status. This should be changed to filter where end_time is in the past.

https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L29

**Comment by pragyajalan** [comment]
https://github.com/ReadyResponder/ReadyResponder/pull/312

**Comment by kgf** [comment]
Resolved by #312
