### ISSUE TITLE
Improve event form to capture who is eligible for this event

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#31]
Some events require a certain level of training, which is contained within the team they're on. When creating an event, have checkboxes (perhaps) to say which departments are eligible. Departments that are not eligible have availability records created with the status preset to "Unavailable", and the reason set as "Ineligible". This would greatly reduce the effort for setting up events. This expects that the changes in time tracking that are described in the Wiki are already implemented

**Comment by kgf** [comment]
The requirements for this have changed to match the new data model. Now this is simply to add the selector to the event forms, and persist it to the database. This would be a have and belongs to many between events and departments. 
Instead of creating unnecessary availability records, we need to change what the event returns as eligible people.

**Comment by Spandana-Sai** [comment]
@kgf can you please explain in-detail?

**Comment by kgf** [comment]
You would need to make the relationship between events and departments, add to the event form to allow someone to choose multiple departments, and finally, change this code to only return people who are in the departments.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L68
Is this enough @Spandana-Sai ? Are you still interested ? This has become a high priority...
Thanks

**Comment by Spandana-Sai** [comment]
@kgf Can you please let me know the deadline. I will be busy till this Dec 16. If you are okay with that I will resume work on 16th Dec and will submit the code.
