### ISSUE TITLE
Info Message about an event

### ISSUE THREAD

**Issue by masukomi** [ReadyResponder/ReadyResponder#310]
We need a new `msg` object that responds to the "INFO" codeword. 

This should provide information about the event in question. 

revised version
```
Event Name: <title> (<codeword>)
Duration: <date+time> to <date+time>
Description: <description>

Available: 1
Partially available: 3
Unavailable: 8
Unknown: 2
```

----------------------------------------------------
initial version
```
Event Name: <title> (<codeword>)
Duration: <date+time> to <date+time>
Description: <description>

Scheduled People (1): 
* Anthony Brown

Available People (3):
* Bob Smith
* Mary Adams
* Thomas Quine

Partially Available People (2):
* Carol Line
* Michael Smith
```

If Scheduled, Available, or Partially Available have no associated people it should just say "NONE"

**Comment by kgf** [comment]
This may need to be two different verbs. `info` would give event meta data. That looks like a lot of info for a text message.  The second might be `roster codeword available` which would give you a list of all the available people.
