### ISSUE TITLE
No validation between application date and start date

### ISSUE THREAD

**Issue by dacharyc** [ReadyResponder/ReadyResponder#313]
Creating some dummy people for my local instance, and I noticed:

I entered an application date of: 2017-01-13
And I entered a start date of: 2006-08-16

RR did not complain about the fact that the start date is before the application date.

The "Duration" is calculated appropriately from the start date, not the application date.

**Comment by antciccone** [comment]
great! I'll take a look at this.

**Comment by kgf** [comment]
@antciccone if you have time, could you please include adding some more people to the seeds rb file? 
Thanks for your help!

**Comment by kgf** [comment]
@antciccone do you still have any interest in this ?

**Comment by cam-ball** [comment]
Hi @kgf, I can do this one!

**Comment by kgf** [comment]
@laurenball That would be great, thanks !
