### ISSUE TITLE
Bad URL when creating new title after creating new title

### ISSUE THREAD

**Issue by dacharyc** [ReadyResponder/ReadyResponder#316]
I created a new title, was taken back to the title page, and clicked the new title button again...

This time, there's a .3 in the URL that shouldn't be there.

<img width="434" alt="screen shot 2017-01-15 at 11 00 25 am" src="https://cloud.githubusercontent.com/assets/1308377/21964013/03edb2b8-db12-11e6-9f27-2dc4b21fb95a.png">

**Comment by dacharyc** [comment]
Did this again to try to recreate...

After you create a new title, you're taken into a page that has details about that title. From there, you can click the New Title button to create a new title. This is where the .X seems to be happening.

<img width="525" alt="screen shot 2017-01-15 at 11 03 26 am" src="https://cloud.githubusercontent.com/assets/1308377/21964040/73e19490-db12-11e6-9abe-a496b9c555d6.png">

**Comment by mxie** [comment]
I'll take this one!
