### ISSUE TITLE
When looking at the target of the Events link, too many are shown

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#321]
By default, it should only show events that are scheduled or in-session. Getting old events should be an additional action. The additional action should appear as a blue button on the left side navigation..

**Comment by sergeimellow** [comment]
I just took a look at this, does this solution suffice? 
https://github.com/ReadyResponder/ReadyResponder/pull/328/files

**Comment by kgf** [comment]
If you could just resolve the issue with having the same page title, that would work.
Thanks

**Comment by kgf** [comment]
Resolved by #328
