### ISSUE TITLE
Top nav menu implementation hides the top of the page

### ISSUE THREAD

**Issue by dacharyc** [ReadyResponder/ReadyResponder#322]
The top nav menu implementation is cutting off the top of the page. This is an issue when I use anchor tags in the Help documentation, because when you click on a link to an anchor tag (which in this case is tied to a header), the text (header) is hidden behind the top nav menu bar instead of below it. 

This is what I see when I click an anchor tag:
<img width="1093" alt="screen shot 2017-01-15 at 1 26 05 pm" src="https://cloud.githubusercontent.com/assets/1308377/21965098/98153902-db26-11e6-9428-3271d9ef4830.png">

If I scroll down an eensy bit, I see this:

<img width="1089" alt="screen shot 2017-01-15 at 1 26 22 pm" src="https://cloud.githubusercontent.com/assets/1308377/21965101/a55b4520-db26-11e6-87f5-a96e335ce44e.png">

I want to see the text (in this case, the header where the anchor tag is tied) below the top nav menu, instead of behind it. In other words, the second image is what I want to see, but the first image is what I am currently seeing.

**Comment by kgf** [comment]
Not sure what has changed, but I don't see this anymore.
