### ISSUE TITLE
Person status does not update Availability

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#359]
If an availability has been entered for a person for an event, and the person's status changes to inactive, they continue to appear as available for the event.

Their availability should not be returned at all if they are inactive.

Code wise: needs to be scoped to active people
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/event.rb#L71

**Comment by abrophy** [comment]
I corrected this by adding an 'active' scope to availabilities, that filters out availabilities for people that are inactive.

I could use your input on whether you'd like this scope to have another name, or have it done some other way.
