### ISSUE TITLE
Edit Availability does not include original person when being edited

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#360]
Edit Availability returns the time/dates but not the person if the person's status had changed.
This will affect cases of editing history after a person's status changes.

**Comment by kgf** [comment]
This is if the person's status changed from Active to Inactive.

**Comment by kgf** [comment]
This line would need to change, and a test
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/availabilities/_form.html.erb#L5

**Comment by nesteves** [comment]
Hi, I would like to help with this issue. It is my first contribution.

I'm thinking of setting up a @people_collection within the controller actions (edit and new) and adding controller specs asserting that @availability.person is included in the collection.

**Comment by kgf** [comment]
Welcome @nesteves !
I don't think you'll need to do anything for new, as there is no existing person at that point. I think all you may need to do is add the existing value of person of that availability to the collection on the form.

**Comment by nesteves** [comment]
I ended up working on the controller, otherwise I would need to either have one form for each action or write some if statements in the view. Both of these options seemed bad.

I haven't got a clue about writing view specs for this case.
