### ISSUE TITLE
Return to Listing button works as back on Person

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#361]
Return to listing on person works as back instead of returning to listing.
In case of editing person, after saving changes, return to listing reopens edit rather than going to list.

**Comment by annadolan** [comment]
I was able to reproduce the bug locally, I'd like to take this on if it's available! I need a little info though, it's unclear where "return to listing" should actually direct to.

**Comment by kgf** [comment]
It should return to the list of people ( The index action ). Back would be even better, but it needs to return to whatever was _before_ the edit, if that makes sense.

Thanks for your interest and help !

**Comment by annadolan** [comment]
@kgf Thanks for the clarification! I'll work on linking back and fall back on linking to index.

**Comment by kgf** [comment]
Resolved by #368
