### ISSUE TITLE
Availabilities are not unique for one person

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#372]
Currently, as of v2.2, someone can send in a text message and create an availability. This works well.

But what happens when they send in another ? It simply adds it without considering what is already in the system. For example, let's say Matt Udy sends in that he's available for Monday, noon to five. He later finds out he has to work, so he sends in `Unavailable` for the same time period. The system will count him as both available ***and*** unavailable. 

As with most things related to time, there are a lot of edge cases, but I'd like to keep this simple at first.

If someone sends in a second Availability record, we should set the status of the first one to `Cancelled` and then record the second one.

The edge cases will come when the times do not line up exactly.

**Comment by abrophy** [comment]
How about a cancel_duplicates method on the availability model that searches for all previous availabilities with the same timespan and sets their status to Cancelled.

Put this method in before_create for availability?

**Comment by kgf** [comment]
That seems like a good start. We can re-use for_time_span method of availabilities.

In this iteration, I only want to cancel if the times match precisely. (BTW, we only go to quarter hour increments, so time should only be that precise. )
