### ISSUE TITLE
text command upcoming should only show events appropriate for viewer

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#375]
Currently the text message 'upcoming' to the system returns all future events regardless of whether the person is not eligible for working the event.
Example a CERT person will see events which should only be shown to MRC personnel.

**Comment by kgf** [comment]
@sa77 you've done a lot of great work for the project. 
This is the only other issue currently in the texting area of the code. Would you be interested?
Thanks for all your help, either way.

**Comment by sa77** [comment]
@kgf sure thing .. i can take a crack at it
