### ISSUE TITLE
Show multiple sets of status boxes for events

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#392]
This is referring to these boxes
![screen shot 2017-03-06 at 10 58 20 am](https://cloud.githubusercontent.com/assets/2431417/25407720/650c42ba-29d9-11e7-9fd6-eca63844b774.png)

In events, the status boxes are quite helpful for knowing how an event is staffed. Currently the event shows only one set, which can be inadequate for events with several departments responding. This issue is a request for one set **per department**. They should be stacked vertically, with the department name to the left. The department short name should replace the word `Personnel` in the screen shot above. They should drop below the event status.

**Comment by kgf** [comment]
This may look slightly different now. There are now also blue boxes showing assignments, but it's still there same ticket.

**Comment by firdausmaarof** [comment]
Hi. I'm interested to work on this one.

**Comment by kgf** [comment]
@firdausmaarof that would be great, thanks. Any questions, feel free to post them here.

**Comment by kgf** [comment]
@firdausmaarof Any questions or updates ?

**Comment by kgf** [comment]
@firdausmaarof Are you still interested in working on this ?

**Comment by kgf** [comment]
@firdausmaarof We haven't heard from you for a while. I'm going to set this back to `Help Wanted`. If you actually _are_ working on it, please post a comment and I'll reverse that action.

**Comment by nesteves** [comment]
Hi @kgf, I would like to take a look at this.

**Comment by kgf** [comment]
That would be great, thanks @nesteves

**Comment by kgf** [comment]
@nesteves have you had any success on this issue?

**Comment by nesteves** [comment]
@kgf had some trouble finding free time for this. I am picking it up again today and looking forward to finishing it no later than this weekend!

**Comment by nesteves** [comment]
@kgf, just a small question, there are 5 status boxes:

* assigned
* available
* partially available
* unavailable
* no response

Are these mutually exclusive? I was working on that assumption writing feature specs for these, but when I create a person that has an assignment related to the event, making her a *assigned* person, it also affects the other 4 statuses, depending on whether I also define an availability, its status (*Available* vs *Unavailable*) and its length.

Thanks!
Nuno

**Comment by kgf** [comment]
Assigned is a special case, it reflects when someone has something to do. The other four boxes are  mutually exclusive. You can be Available, partially available, unavailable, or unknown, but only one.
Thanks for your help.

**Comment by kgf** [comment]
Fixed by #616, thanks to @nesteves
