### ISSUE TITLE
In Person - Availabilities view, sort by start time is wrong

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#395]
In Person #Show - Availabilities section, sort by start time: sorts time/date as string, ordering the entries by first digits.
Oddly enough, sort by end time works correctly.

**Comment by myrridin** [comment]
I took a shot at this with the above PR. It resolves the issue, though the `<time>` tag may have been providing functionality I'm unaware of.

I'm also not sure about including the database cleaner change with this, but I was unable to pass the test suite without that change.

**Comment by kgf** [comment]
Thanks for your help. I'll take a look.
