### ISSUE TITLE
On event, remove template from category choices

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#397]
Events have categories, such as Meeting or Admin. Being a template is a different question, and has a seperate field. `Template` should not be a choice.

**Comment by itroman** [comment]
Happy to work on this if it's still up for grabs.

**Comment by kgf** [comment]
That would be awesome, thanks for your help !
If you have any questions, please ask.

**Comment by kgf** [comment]
Closed by #398 
Thanks, @itroman !
