### ISSUE TITLE
When entering new person, if status is blank, info is lost on attempt to save

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#403]
When entering new person, if status is blank, info is lost on attempt to save.
When Validation for status fails, error message appears with blank form.

**Comment by ghost** [comment]
This seems to be fixed. JS validation kicks in before form submits, no info lost. Close this?

**Comment by kgf** [comment]
Thanks for the update. This does seem to be fixed.
@VanAuken could you please test this ?

**Comment by VanAuken** [comment]
Tried it today.  Works beautifully.
Thanks!
