### ISSUE TITLE
Allow admin to verify timecards from the view

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#432]
Timecards are generally entered through SMS text messages. When they are completed, they are in an Unverified state. They stay there until a supervisor edits the record. I am hoping to change this to being able to Verify from the view. This button should be hidden based on Cancancan permissions. The button would change the status value from `Unverified` to `Verified`.

@goldenhub77 has offered to help. Thanks !

**Comment by goldenhub77** [comment]
@kgf I sent a pull request to resolve this issue.

**Comment by kgf** [comment]
Thanks for your help. I have commented on the PR

**Comment by goldenhub77** [comment]
@kgf I took your feedback and made the applicable changes. All tests have passed.

**Comment by kgf** [comment]
Closed by #433
