### ISSUE TITLE
On Person view, remove 'Return to Listing' button

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#440]
On Person view, 'Return to Listing', blue button on side navigation, is actually back, button will reopen edit if that was last action.

**Comment by kgf** [comment]
Removing the button will be an acceptable solution to this problem

**Comment by t2013anurag** [comment]
@VanAuken @kgf Can i take it?

**Comment by kgf** [comment]
@t2013anurag that would be great, thanks

**Comment by kgf** [comment]
@t2013anurag Any updates or questions ?
