### ISSUE TITLE
On events#index, use check boxes to filter events

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#441]
This would be instead of using different query strings currently. The events listing is displayed in a datatable, which I believe provides some option for this.
There would be three checkboxes; current, past, templates

Would this interest you, @goldenhub77 ?

Feel free to ask questions...

**Comment by goldenhub77** [comment]
@kgf Yes I am interested, I will take a look later today and follow up.

**Comment by goldenhub77** [comment]
@kgf I have some questions listed below: 
1. When you are speaking about current and past events, will that being taking into consideration the date/time and status, just status, or just date/time?
 
2. Do you want me to completely separate the templates as they are technically not true events?(also I created a template as a test, but it does not appear to allow me to apply it when creating a new event.)

**Comment by kgf** [comment]
@goldenhub77  templates can only be used if they have a status of 'In-session'. This is a bit of a landmine for the end user. Templates should have statuses of `Active` and `Inactive` only.
Currently past events would only be date/time, but that should already be defined here -=>
 https://github.com/ReadyResponder/ReadyResponder/blob/development/app/controllers/events_controller.rb#L7
The templates can be their own checkbox, but it needs to be more obvious from the index view that a line represents a template. Perhaps highlighting the line ?

**Comment by goldenhub77** [comment]
@kgf My tests require javascript and the current configuration is not working properly. I have fixed the issues so my tests will run but I wanted to make sure you were ok with me changing to the selenium-webdriver and chromedriver-helper to run JS tests instead of poltergeist as it is much more reliable.

**Comment by goldenhub77** [comment]
@kgf also please send me an invite to the slack channel.

**Comment by kgf** [comment]
How do your changes affect the rest of the test suite ?
Send me the email you would like me to invite to kfallon@readyresponder.org

Thanks for your help.

**Comment by goldenhub77** [comment]
@kgf I sent a response via email, just let you know if you received it.

**Comment by kgf** [comment]
Closed by ui_v3 merge into development
