### ISSUE TITLE
When creating a new availability, it should cancel others shadowed. 

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#449]
Currently, a volunteer can text in that they are available using the ID code for an event, and that will be recorded as an availability with the same start and end times as the event matching that ID code. Note that there is no parent-child relationship between the two. If the volunteer then sends in another text saying unavailable, the first Availability will be found and it's status changed to cancelled. The new one will be saved. Great.

But,
If the volunteer sends in Available, as in the first example, and then sends in `Unavailable custom` ( `custom` allows them to sign-up for any arbitrary times ) for a period greater than the first record , both records will exist and conflict with each other. This is confusing and bad. This issue requests that if the new `custom` availability completely covers one or more existing availabilities, the existing ones should all be set to cancelled before the new one is saved.

@danielstrimpel is this of interest, since you were just in this area of the code ?

**Comment by ghost** [comment]
Yep, I'll take this.

**Comment by danielstrimpel** [comment]
In trying to recreate the issue, I tried to create a new person on my local dev machine to have my phone number. However, it wouldn’t let me create a person on submit, saying ["Phones content is invalid”] even though all fields were filled in. I’d make an issue for this, but I want to make sure it’s not just happening on my local setup for some reason, and I haven't found where the production URL is yet (help with that please?).

Another possible issue: trying to edit an existing person to add phone info doesn’t work, because the section is missing from the form as in this screenshot:
![ready](https://user-images.githubusercontent.com/21265184/30814675-dac08b7e-a1de-11e7-940f-b74fc21b4e2d.jpeg)

Dunno if that’s sposed to be that way, or if its another issue.

**Comment by ghost** [comment]
In trying to recreate the issue, I found a bunch of problems with the New Person form. 

- [ ] Complains about wrong phone info incorrectly and won't submit (so can't create new person with my phone number to test).
- [ ] Edit person has no fields for phone info ( so can't add my phone number to existing person)
- [ ] In phone info, label for number says “content” (should be "number")
- [ ] Status choice “invalid” seems strange, why would I want to enter an invalid number? Same thing with email.
- [ ] What are "old comments" for a new person?
- [ ] I can't enter text into the “titles” text box
- [ ] DOB field: calendar doesn’t pop up

Not sure if this is just on my local dev machine for some reason, or I somehow have outdated code (I'm up to date with development branch). I'd also like to compare with production but as of now I don't know the URL since it doesn't seem to be on the readme and googling Ready Responder turns up a bunch of similar sites, not sure which is this one. 

If these are bona fide issues ("low-hanging fruit"), I can make them issues and fix them. Waiting for direction on this.

**Comment by kgf** [comment]
It complains about wrong phone number because the hint is incorrect. The correct format is `+16175551212`, so that it can integrate with Twillio.

The second is a known bug, hasn’t risen to the top yet.

Number would be better over content

The invalid status is in case a number goes out of service. It not appropriate for a new record, but for editing, it’s good. And we found invalid more useful than deleting it, as sometimes they would come back. Also, at some point we want the code to set phones to invalid as well.

Old comments are a text field on the actual person record. Someone started adding comments as a child of person, which is desired. ( Then multiple people can make comments, they’ll be traceable and dated.) Sadly, they did not finish this code effort.

Titles - That is actually a multi-select. Go to Admin - Titles to ad some choices, or better, add them to the seed.rb. Shelter Manager might be a good choice.

DOB calendar was found to be a hinderance, because it takes too long to navigate to the correct year.

I hope this helps answer these questions. There are issues in for some of these, but certainly not all. I’d love help on any of this !

Thanks
Kevin

**Comment by ghost** [comment]
Thanks for the info Kevin. FYI I have an urgent project to finish by the end of tomorrow, so won't get to RR stuff till then. Appreciate your patience.

**Comment by kgf** [comment]
Hey, no problem. All help is appreciated, especially with good communication like this !

**Comment by kgf** [comment]
@danielstrimpel were you successful in your urgent project ?

**Comment by ghost** [comment]
Well, I didn’t get a job offer from them. But in the sense of having fun and learning a lot (of React, specifically), I’d say it was pretty successful.

I have time to keep contributing to RR. On this particular issue, I seem to keep running into other bugs that are preventing me from reproducing the problem which is frustrating...

Do you have any interest in me building out a new, non-trivial feature where I can get my hands dirty and go deeper with Rails? What are you priorities for RR right now?

**Comment by kgf** [comment]
Sorry to hear about the job situation. 
I'm happy with any help here. If this one is aggravating, we can find something else, and I'll put this up as help wanted again.
Would this be of interest ?
https://github.com/ReadyResponder/ReadyResponder/issues/507

**Comment by ghost** [comment]
Yes, I started working on it.

-
Daniel Strimpel
dastrimpel@gmail.com <mailto:dastrimpel@gmail.com>
Blog: https://medium.com/@dastrimpel
Github: https://github.com/danielstrimpel

**Comment by ghost** [comment]
Currently upload seems to work. Still working on image display problem where images are not being found in their upload folders.

**Comment by kgf** [comment]
@danielstrimpel Is this comment on the correct issue ?

**Comment by kgf** [comment]
@vcavallo, is this of any interest ? Very backend....

**Comment by kgf** [comment]
Note that you can get into the same situation by paths that do not include `available custom`. It should probably be a save hook. Not thought it through enough to know if it should be before or after.

**Comment by ghost** [comment]
Sorry, that was pertaining to #507

**Comment by nesteves** [comment]
@kgf, can I help with this issue?

**Comment by kgf** [comment]
@nesteves that would be great ! As you can see, this is a high priority.

Thanks for your help

**Comment by nesteves** [comment]
@kgf, what should happen when the new availability partially overlaps an existing one?

**Comment by kgf** [comment]
That's tricky, and should probably be a different issue. Part of it depends on if the two are the same status, available vs unavailable. If they are the same status, you could cancel the original, and expand the new one to the span of the two combined.

**Comment by nesteves** [comment]
@kgf I am using postgres ranges for *overlaps*, *contains* and *is contained* queries. This forces me to make a simple assumption about the time interval boundaries, which I will treat as **[** start_time, end_time **[**, the interval includes the value of *start_time* and excludes the value of *end_time*. This way, contiguous ranges do not overlap each other. I am also assuming that a person's availabilities (Available and Unavailable) never overlap in the database - which warrants a validation.

I have 2 questions I would like you to comment on:

(1) For the overlap issue with availabilities, can you weigh in on the following solution

* if the new availability *contains* any existing ones, cancel those, no matter their status
* if the new availability *overlaps* any existing ones, that is, covers a part of their duration
  * having the same status, cancel the existing one and expand the new one so it covers both
  * having different statuses, move the existing one's boundary so they become contiguous
* if the new availability *is contained* by an existing one
  * having the same status, return an error
  * having different statuses, break the old availability into 2 and accommodate the new one

(2) Finally, is this behavior needed when using the web interface? Personally I don't think so, as the user can easily receive the validation feedback, check what availabilities he has defined and change her input accordingly.

**Comment by kgf** [comment]
Thanks for your help. 
Question 1: You should proceed with thoe assumptions. I worry slightly about when things overlap, but the implementation you have outlined is SO much better than where we are now, I think you should proceed.

I agree this is more important for the remote, non-web UI, but I would think it would be almost harder to not implement for all cases. Would this be model methods ?

Thanks again,
Kevin

**Comment by nesteves** [comment]
The model will just expose the necessary scopes to find overlaps and include a validation to ensure no overlapping availabilities are inserted.

As for the creation of the availabilities given the 3 scenarios, I'm thinking of wrapping the logic in a service object. That way we can easily integrate it where we want to, while keeping the model class relatively thin.

**Comment by kgf** [comment]
I usually only think of using a service object when I have more than one model. I'll be interested to see the approach.
