### ISSUE TITLE
Upgrade from Rails 4.2 to Rails 5.0

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#450]
We are currently on Rails 4.2. There are features we would like to develop that would be a lot easier using Action Cable and other features available in Rails 5. Therefore, we would like to upgrade.

Since I don't expect anyone to do the entire ticket, I have created a branch for this effort.
`upgrade_from_rails_4_to_rails_5` Any progress should be PRed against this branch.

A good place to start.
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0

Thanks for your help.

**Comment by kgf** [comment]
This may also prove useful.
http://www.ready4rails.net/
https://stackoverflow.com/questions/38442248/how-to-upgrade-from-rails-4-2-6-to-rails-5-0

**Comment by phsacramento** [comment]
Doing

**Comment by kgf** [comment]
Thanks for your help @henriquesacramento

**Comment by sa77** [comment]
@kgf i can help out on this if it is not being worked on.
@henriquesacramento are you currently working on this ?

**Comment by kgf** [comment]
@sa77 We have not heard back from Paulo yet. Could you please start on this ? It is actually probably the highest priority issue, as there are some other tickets I will create once this is complete.
Please update this issue, so that if Paulo is also working on it, we can coordinate.
Thanks for your help.
Kevin

**Comment by phsacramento** [comment]
@kgf I'm doing this. 

Update:
the update has broken some dependencies, I'm working on it.

**Comment by kgf** [comment]
Ah, that's great @henriquesacramento 
Thanks for the update.
As mentioned above, there is a feature branch for any partial PRs -> `upgrade_from_rails_4_to_rails_5`

**Comment by phsacramento** [comment]
@kgf Now we need use strong parameters in project, the gem protected_attributes in no longer compatible with rails 5.
So change all controllers in entire application is need

Update:

@kgf and fix all tests suite

**Comment by phsacramento** [comment]
@kgf Now in rails 5 belongs_to association is required, is not longer possible create record without they respective associations. I will add a fallback for that feature.

ex: 

```
belongs_to :contact, class_name: "Person", optional: true
```

Make sense?

**Comment by phsacramento** [comment]
![captura de tela 2017-10-03 as 12 55 04](https://user-images.githubusercontent.com/2622863/31135029-3905751c-a83a-11e7-81ad-e9dd115a6a83.png)

**Comment by kgf** [comment]
Ouch ! That's a lot of red.
If you want to PR what you have, I can make issues to resolve the controllers. Ideally you could fix one, and I can cite it as an example of what right looks like ?
Or perhaps you prefer a different approach ?

**Comment by kgf** [comment]
Sorry, this one did not completely make sense. 

> Now in rails 5 belongs_to association is required, is not longer possible create record without they respective associations.

**Comment by phsacramento** [comment]
Rails 5 has changed the belongs_to relation to require presence by default. [Check this PR](https://github.com/rails/rails/pull/18937)

So now ```required: true``` is deprecated:

```
belongs_to :contact, class_name: "Person", required: true # deprecated => `required: true`
```

**Comment by kgf** [comment]
Thanks, I'll take a look.

**Comment by kgf** [comment]
@henriquesacramento I took a look in the codebase for `required: true` on associations, and I did not find any examples. So that's good news !

**Comment by phsacramento** [comment]
Rails 5 makes belongs_to association required by default.
![captura de tela 2017-10-03 as 19 03 40](https://user-images.githubusercontent.com/2622863/31151933-2d71ea88-a870-11e7-9dc7-04a231857eef.png)

**Comment by kgf** [comment]
Ah, now I understand. We'll need to add `optional true` to a bunch of these. Are you handling that, or would you like help ?
Not all events will have templates, so that one should be optional.

**Comment by phsacramento** [comment]
Update:

![captura de tela 2017-10-03 as 20 28 49](https://user-images.githubusercontent.com/2622863/31153806-83bc4736-a879-11e7-8899-d09fa4b2572c.png)

**Comment by kgf** [comment]
It looks like you're changing it to an integer? Right now it is hours and quarters of hours, which works well. No event would go into thousands of hours.

**Comment by kgf** [comment]
@henriquesacramento Any updates ? Is there anything we can do to help ?

**Comment by phsacramento** [comment]
@kgf I will update the current branch, and you tell me how can you help me.

**Comment by kgf** [comment]
Excellent, thanks !

**Comment by kgf** [comment]
I have merged this into a feature branch. Someone is manually testing this, given the extent of the changes.

**Comment by kgf** [comment]
The current plan is to test the current head of development, deploy that as 2.7.0, then test and merge this into development.

**Comment by kgf** [comment]
We have been successful! Thanks to all who helped!
