### ISSUE TITLE
Deprecated seeds

### ISSUE THREAD

**Issue by xarlybovi** [ReadyResponder/ReadyResponder#456]
Hi, I was setting up the project locally until this error executing `bundle exec rake db:seed`

> NoMethodError: undefined method `find_or_create_by_name' for #<Class:0x00000005be6d38>

I have replaced some finders acording to [the rails version](https://github.com/rails/rails/blob/4-2-stable/guides/source/active_record_querying.md#find_or_create_by) and now it works for me.

**Comment by kgf** [comment]
Resolved by #457. Thanks @xarlybovi
