### ISSUE TITLE
unable to save a person after editing.

### ISSUE THREAD

**Issue by DJG86g** [ReadyResponder/ReadyResponder#46]
i was editing a already existing person. when i went to save i received

> unknown attribute: phones

this is probably related to the recent work in channels apposed to phones.
app/controllers/people_controller.rb
line #122
if @person.update_attributes(params[:person])
https://github.com/kgf/lims/blob/development/app/controllers/people_controller.rb#L122

**Comment by kgf** [comment]
Would this help ?

http://stackoverflow.com/questions/6599129/subclassing-activerecord-and-maintain-subclass-after-db-fetch

**Comment by kgf** [comment]
Actually, this also looks quite relevant

http://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html

**Comment by corincerami** [comment]
I'll have a PR open for this soon.

**Comment by kgf** [comment]
This was resolved by work that was done around channels. Unsure which specific PR.
