### ISSUE TITLE
Transition `Event` menu to split drop down.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#466]
This would allow a single click to get you to current events, then a checkbox to look at recent events. Under the drop-down would be Templates and archives

**Comment by kgf** [comment]
@goldenhub77 Thanks for your help.

**Comment by goldenhub77** [comment]
@kgf FYI, PR has been submitted and still pending checks.

**Comment by kgf** [comment]
This was resolved by #497
