### ISSUE TITLE
New Person form, in phone information, label should be 'number' not 'content'

### ISSUE THREAD

**Issue by ghost** [ReadyResponder/ReadyResponder#482]
In phone info, label for number says “content” . Should be number.

**Comment by kgf** [comment]
Any solution for this needs to NOT change the label for email.

**Comment by kgf** [comment]
There is code here 
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/people/_channel_fields.html.erb
But I'm not sure it's still in use. There is also
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/channels/_form.html.erb
that I think is in use, by both the phone and the email.

**Comment by SGospodinov** [comment]
@kgf, I believe 5b55eab resolves this one as well.

**Comment by kgf** [comment]
@SGospodinov Thanks for your help. Yes, this issue is resolved
