### ISSUE TITLE
Placeholder text gives wrong phone number format

### ISSUE THREAD

**Issue by ghost** [ReadyResponder/ReadyResponder#483]
Form validates numbers with a + (country code) prefix, e.g. in US +15555555, but placeholder is not in this format.

**Comment by tegon** [comment]
Hi! Can I tackle this one?

**Comment by kgf** [comment]
@tegon Sorry, there is already a PR in for it. If there is something specific you'd like to work on ( Front-end back-end ) I can probably point you to an issue.
Thanks for your interest
Kevin

**Comment by tegon** [comment]
@kgf Sure thing, what do you have open for backend?
