### ISSUE TITLE
On person#edit, should be able to add additional phones

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#485]
Currently, you can not add additional ways to contact people. There is room for one phone, and one email. In fact, the backend structure supports unlimited channels. 
The solution is to give people the ability to add a new channel beyond the existing two.

Fell free to ask questions.

**Comment by SGospodinov** [comment]
I'll be happy to take work on this one. I have the following questions:
1. Can I use additional gems namely https://github.com/nathanvda/cocoon?
2. Do you need this feature to be tested?

**Comment by kgf** [comment]
Using that Gem is OK.
Tests are always good !

Thanks for your help !
Kevin
