### ISSUE TITLE
Create a new event icon in the events view

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#488]
Create a new event icon in the events view
This will replace the blue 'New Event' button. The icon should be a plus sign and should have an open source compatible license.

**Comment by VanAuken** [comment]
Here you go @goldenhub77 .  Thanks for your help.

**Comment by goldenhub77** [comment]
@VanAuken I used the ascii character to make the + symbol which will not need a license

**Comment by goldenhub77** [comment]
@VanAuken @kgf PR request #492 for this issue.
