### ISSUE TITLE
Text response for `Upcoming` should show status icons.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#493]
Currently people can text `Upcoming` to their installation of Ready Responder. This will give them a listing of the events in the near future. I would like to add an icon at the beginning to provide additional info.

Show a blue diamond if they have been assigned a task for that event.
Show a grey question mark if they have not responded
Show a red X if they have responded `Unavailable`
Show a green checkmark if they have responded `Available`

NGrok could be a very useful tool to achieve these results.

**Comment by kgf** [comment]
@sa77 Since Paulo is handling the upgrade, I wondered if this would be of interest ?

**Comment by sa77** [comment]
@kgf i can look into it .. can you give me some pointers how to get started on this ? 

> Currently people can text Upcoming to their installation of Ready Responder. This will give them a listing of the events in the near future. I would like to add an icon at the beginning to provide additional info.
- how to simulate sending a text to the app ? which files in the codebase handle this ?
- the icons .. where does the icons need to be displayed on the app (relative `url` would help) ?

**Comment by kgf** [comment]
Answering from my phone, so this may be a bit brief. The icons will be sent via text message to the user. For this issue, there would not be a browser. Ngrok may be able to help with that. I used it, worked pretty well.
The icons will be what's available in a text message client. I post a sample tomorrow.
Take a look here
https://github.com/ReadyResponder/ReadyResponder/blob/6d8069356db2b79e281702ebb2628074ec0c90f0/app/services/msg/upcoming.rb

**Comment by kgf** [comment]
Here are some log entries
Started POST "/texts/receive_text"
Processing by TextsController#receive_text as */*
🔷 Assigned
https://emojipedia.org/large-blue-diamond/

✅ Available
https://emojipedia.org/white-heavy-check-mark/

⚠️ Partially Available
https://emojipedia.org/warning-sign/

❌ unavailable
https://emojipedia.org/cross-mark/

? Unknown
No emoji, just a standard `?`

You may be able to just paste these into the response strings.
I hope this helps. Thanks for your efforts !

**Comment by sa77** [comment]
@kgf are you referring to the `status` of `Availability` model (as in `Person.last.availability.status`) ?

**Comment by kgf** [comment]
Yes, mostly. The assigned would not be availability based. We have code that I think you can use already. The classes for the rows of the availability table on an event use the same logic. ( And the same colors, which I would like to keep consistent. )

**Comment by sa77** [comment]
@kgf i've got something like this .. good to go ?

![image](https://user-images.githubusercontent.com/4640354/31229705-53cd1eb8-aa01-11e7-87ef-d16b31eba658.png)

**Comment by kgf** [comment]
That does look good. Is the unavailable case handled as well?

**Comment by sa77** [comment]
yes .. unavailable should work as expected

**Comment by sa77** [comment]
i'll create a new PR branched off after rebasing with latest ReadyResponder/ReadyResponder:development

**Comment by kgf** [comment]
Awesome, thanks
