### ISSUE TITLE
Add last editor to event show

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#498]
We'll want this on all things eventually, but event show for now.

**Comment by tuwukee** [comment]
Didn't notice that there's already a PR for that :)
Closing #502

**Comment by kgf** [comment]
@tuwukee Thanks for your help. I try to add `Claimed` labels to the issues. Would you be willing to make the same change to other pages ? We want to have that everywhere.
Notifications is another place it is lacking. I created a new issue, if you're interested
https://github.com/ReadyResponder/ReadyResponder/issues/503
