### ISSUE TITLE
Remove person and item associations from factory

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#500]
The code to change is here
https://github.com/ReadyResponder/ReadyResponder/blob/development/spec/factories/inspection.rb#L3
Obviously, you'll need to ensure the test suite is still working.

**Comment by ale7714** [comment]
@kgf happy to help with this issue. You mention remove `person` and `event`. But i don't see the `event` association on this factory. 
```
  factory :inspection do
    person
    item
    inspection_date Date.tomorrow.strftime('%Y-%m-%d')
    status "Passed"
  end
```

**Comment by kgf** [comment]
@ale7714 Great, appreciate your help. It was my mistake, it should have read `Remove person and item`

**Comment by ale7714** [comment]
@kgf no worries! will look into this later today.

**Comment by kgf** [comment]
@ale7714 Have you had any success ? Any blockers ?

**Comment by ale7714** [comment]
@kgf sorry had something unexpected come up. But i will look into this tonight or tomorrow. Sorry for the delay.

**Comment by kgf** [comment]
@ale7714 No problem, things happen. Thanks for your help !
