### ISSUE TITLE
On certification#show, remove "Return to List" button

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#504]
This button does not do what people expect.

**Comment by mohanck** [comment]
I'd like to try this out. I intend to remove the ```sidebar_button_link``` from the content bar in show.html.erb for certs. Let me know if this sounds right. Thanks!

**Comment by kgf** [comment]
@mohanck That sounds right. Thanks for your help !

**Comment by goldenhub77** [comment]
@kgf @mohanck FYI, with the merge of ui_v3 into Dev all you need to do is remove the sidebar yield and it will default to to col-md-12 in application.html.erb. If there are some other ideas to change the that is great but you can start there.

**Comment by kgf** [comment]
I don't think that was the last button on that page.

**Comment by mohanck** [comment]
@goldenhub77 @kgf Removing the sidebar yield also gets rid of the ```Edit Cert``` functionality. Do we want really want to remove Edit functionality too?

**Comment by goldenhub77** [comment]
@mohanck @kgf  You are right, about losing that button as well. I wasn't sure if Kevin wanted to repurpose that button in a different way instead of using the sidebar. He has been having me create a circular add button instead of 'new object button' in the side bar.

**Comment by mohanck** [comment]
@goldenhub77 Thank you for your reply. I am thinking of removing the ```sidebar_button_link``` for now. I also noticed that the functional test for ```show``` only checks for ```success``` response. I think having a class for the ```Edit``` button and checking its presence would be more beneficial in the test too. I could add that, but wanted to know your and @kgf thoughts before I did.

**Comment by kgf** [comment]
@goldenhub77 has correctly anticipated where we're going with the UI. I will want to eliminate the `Edit Button` at some point. I also want to have the UI be consistent, and I have not figured out how to redefine the buttons in the sidebar of the `event#show` page. That page have several add buttons.
We are eliminating the sidebar now in the index views.
Having said all that, yes, please proceed with only removing the one incorrect button.

**Comment by mohanck** [comment]
@kgf Thank you, I will submit the PR. What are your thoughts on changes in test?
```I also noticed that the functional test for show only checks for success response. I think having a class for the Edit button and checking its presence would be more beneficial in the test too```

**Comment by kgf** [comment]
Any improvements to the test are always welcome. Checking that the test person's name appears on the page would be good.
Thanks for your help.
Kevin
