### ISSUE TITLE
NoMethodError on text notification send

### ISSUE THREAD

**Issue by ghost** [ReadyResponder/ReadyResponder#506]
![notification_nil](https://user-images.githubusercontent.com/21265184/31189451-49ab7070-a906-11e7-965c-ba50249570d8.jpeg)

Rails error on submitting a new notification to be sent out via text. @client seems to be nil. Maybe my local environment is missing Twilio credentials? Are there configuration instructions that need to be added to "Getting Started" to make this work locally?

**Comment by kgf** [comment]
We should add a guard to check for a `nil` client. 
Will need to research what the possible solutions might be...
