### ISSUE TITLE
Add minimum title to an event

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#510]
Many groups such as this will have events where everyone should attend, and will also have management meetings where only specific leadership should attend. We are looking to add a dropdown to the event showing a list of all titles from all departments ( where `manage_people` is true) in numerical order. The default value should be the lowest choice. 
When someone does `Upcoming` from a text message, they should only see events for their department, and only events where the minimum level is lower than their title level. There should be no filtering in the views of the web UI at this time.

Levels are currently defined in the model, here
https://github.com/ReadyResponder/ReadyResponder/blob/b38950c24f73ae3075107b3cf9d4c26122f2d266/app/models/person.rb#L55

**Comment by andyvh** [comment]
Hi! I'd love to try to help address this, if you don't mind! I'm having a little trouble getting bundler to install properly, though... 

![bundlerproblems](https://user-images.githubusercontent.com/19498379/31214304-84813032-a95f-11e7-8d2d-3225f9397fe7.png)

Any guidance on where to go from here would be greatly appreciated!

**Comment by kgf** [comment]
That looks like an error between you and Ruby gems server. It may be transient, I would recommend trying again.

**Comment by andyvh** [comment]
It would appear to still be an issue... I'm gonna look into it more now, though!

**Comment by andyvh** [comment]
I've found that one might be able to circumvent it by specifying a Bundler version; which version of Bundler are you using?

**Comment by kgf** [comment]
You can tell by looking at the very last lines of gemfile.lock
BUNDLED WITH
   1.15.4

**Comment by kgf** [comment]
I certainly could be wrong, but I still think this may be an issue with your local setup.

**Comment by andyvh** [comment]
Ok, you were right, and I fixed it, but now I'm encountering another issue with the db:schema:load command; I didn't see any instructions to change it from "lims_development," but I'm told that the database doesn't exist...

**Comment by kgf** [comment]
I'm curious, what was the issue?

For the database setup, you need:
bundle exec rake db:create
bundle exec rake db:schema:load
bundle exec rake db:seed

**Comment by andyvh** [comment]
I'm seeing that permission to create the database was denied...
![screenshot from 2017-10-06 13 20 44](https://user-images.githubusercontent.com/19498379/31296992-3304922c-aa99-11e7-8452-1d909f0126c7.png)

**Comment by kgf** [comment]
If you look at the top line, you'll see the user and password is nil. You'll need to fix that by updating `config/database.yml` Do not commit those changes as part of your PR.
Thanks for your help.

**Comment by andyvh** [comment]
Understood! On it!
No worries, sorry to have been a problem...

**Comment by kgf** [comment]
Not a problem, we're a friendly project
Glad I could help.

**Comment by andyvh** [comment]
May I join the Slack? This project is something that I find myself personally invested in.

**Comment by andyvh** [comment]
I'm also still having trouble, even having edited the config/database.yml...

**Comment by kgf** [comment]
@andyvh What email ?

**Comment by andyvh** [comment]
advanheuit@gmail.com

**Comment by kgf** [comment]
Sent

**Comment by andyvh** [comment]
Thanks!

**Comment by kgf** [comment]
@andyvh Any further questions ? Any success ?!?

**Comment by andyvh** [comment]
I'm trying to track down why the test cases are now failing...
