### ISSUE TITLE
Text to info should show next assignment

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#514]
When an end user texts `info idcode` currently, they get generic details on the event. It would be good if they got these details, and also their personal assignment, assuming they have one. It should be the next assignment that is current, meaning the **end_time** for the assignment is > now.

Any questions, please ask.

**Comment by kgf** [comment]
@sa77 You were just in that section of the code. Any interest ?

**Comment by sa77** [comment]
@kgf sure .. this is the current response on `info idcode` .. can you give me a template what content you want to add into it ?

> Event Name: fooz title (hobby3)
> Duration: 10/15/2017 06:44 to 01/13/2018 06:44
> Description: fooz
> 
> Available: 1
> Partially Available: 0
> Unavailable: 0
> Unknown: 0

**Comment by kgf** [comment]
If you could change it to: (Shortening some of the text...)

> ~Event~ Name: fooz title (hobby3)
> ~Duration:~ 10/15/2017 06:44 to 01/13/2018 16:44
> Description: fooz
> 
> Available: 1
> Partially Available: 0
> Unavailable: 0
> Unknown: 0
> 
> Your Assignments:
> 10/15 1000-1145 Set up shelter
> 10/15 1200-1600 Staff medical intake station

This assumes that there are two active assignments for this person at this event to set up the shelter and staff medical intake.

Any other questions ?
Thanks for your help !
Kevin
