### ISSUE TITLE
On event#show availabilities, it should be short title, not full title

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#515]
This provides more room for more relevant info, and fits smaller displays better. 
For bonus points, the `Unknown` table below should have the same change from ID to short title.

**Comment by kgf** [comment]
See issue #454

**Comment by dusty-wil** [comment]
Hi @kgf, I'd be interested in looking at this, if that's OK. I'm pretty new to ruby, but am interested in learning.

**Comment by kgf** [comment]
That would be great, @dusty-wil . We're happy to help. 
Post here if you have questions.

**Comment by dusty-wil** [comment]
@kgf Ok, thanks for letting me contribute on this! I think I've got it, but I just want to make sure I'm on the right track. 

This is referring to the event availabilities tab, and the tables of people who are available to respond to an event, and the table of people who haven't yet indicated that they're available (No Response). If that's the case, I think I've got the changes ready.

**Comment by kgf** [comment]
That is all correct

**Comment by dusty-wil** [comment]
@kgf Ok, I was about to make the PR, but I noticed when I run rspec, I get some failures. These seem to be due to the version of chrome I'm using (my dev environment is on a ubuntu server):

Should I try to address these before I make the PR?


Failures:
  1) Events search finds no results
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  2) Events search finds template event
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  3) Events search finds current event
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  4) Events search finds archive event
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  5) Events displays a template
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  6) Events displays the course if category is training
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  7) Events displays all events
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  8) Events displays checkboxes current, past, templates on index page
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

  9) Events creates events
     Failure/Error: visit new_user_session_path

     Selenium::WebDriver::Error::UnknownError:
       unknown error: unrecognized Chrome version: HeadlessChrome/61.0.3163.100
         (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-87-generic x86_64)
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/chrome/driver.rb:58:in `initialize'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `new'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:46:in `for'
      /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:19:in `browser'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/selenium/driver.rb:51:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/session.rb:240:in `visit'
      /var/lib/gems/2.3.0/gems/capybara-2.8.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
      ./spec/support/authentication_helper.rb:9:in `sign_in_as'
      ./spec/features/events_spec.rb:5:in `block (2 levels) in <top (required)>'
      ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'

**Comment by kgf** [comment]
That does _*look*_ like the version of chrome being an issue. Go ahead and make the PR, we'll see what Travis makes of it...

Thanks for your help.
Kevin

**Comment by dusty-wil** [comment]
@kgf looks like it passed!

**Comment by kgf** [comment]
It did pass, you were right. Small change requested
