### ISSUE TITLE
Transition People menu to split drop down

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#516]
The People menu is currently a drop down. It should become a split dropdown.

The default action should take you to a view that has all active people. There should be multiple checkboxes, all selected by default for all departments that manage_people. There should be a second group of checkboxes, one for Active, selected by default, and another for On Leave, deselected by default.

The first option under the drop down should include `Applicants`, which should have two checkboxes. One, selected, should be applicants. The other should be unchecked, for prospects.

The second option under the dropdown should be Inactive, which are statuses Inactive and Declined. It should have checkboxes for Departments, all selected by default. It will need to get the department values from the People, as you could have someone that is from a department no longer managing_people.

The third, and probably final option, is Everybody. Checkboxes for Departments form the data, all selected by default.

That's a lot, feel free to ask questions !

**Comment by kgf** [comment]
Thanks to @goldenhub77 for taking this on.

**Comment by goldenhub77** [comment]
@kgf Sorry about the delay. It was a hectic day. I am going to create a PR that should be ready for assessments

**Comment by goldenhub77** [comment]
@kgf What I had was ready but the checkboxes are going to take longer.

**Comment by kgf** [comment]
No problem, thanks for all your help.
This PR that @pcai did recently may help yo with finding the correct peartments for the `Active` default view.
https://github.com/ReadyResponder/ReadyResponder/pull/462
Kevin

**Comment by goldenhub77** [comment]
@kgf PR submitted https://github.com/ReadyResponder/ReadyResponder/pull/536
