### ISSUE TITLE
Validates person has a department

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#528]
Everyone needs to belong to a department. 
Ideally, if there is only one department, creating a new person should default to that department

**Comment by amirkarimi** [comment]
Can I work on this issue?

**Comment by VanAuken** [comment]
That would be great ! Thanks @amirkarimi

**Comment by amirkarimi** [comment]
Done https://github.com/ReadyResponder/ReadyResponder/pull/530

**Comment by ivanfrias** [comment]
@VanAuken  please close this so that we all know which ones are still available.

**Comment by kgf** [comment]
@ivanfrias I expect we will close this today. 
However, we do use the `Help Wanted` and `Claimed` tags on the issues to help with knowing what's available.
Thanks for your interest in our project !
Kevin
