### ISSUE TITLE
When showing an event, course is hidden at first

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#532]
When you are looking at an event, there is JS to show the instructor if the event type is changed to training. This works well, but....
When you first open a training event, the course and instructor are hidden. This issue is to change that.

**Comment by kgf** [comment]
@ThomasCarlson This is a follow-on to your JS work earlier.
Thanks for your help.

**Comment by ThomasCarlson** [comment]
hmm.  if you are referring to the attached, it looks ok to me:

![screen shot 2017-10-12 at 3 47 32 pm](https://user-images.githubusercontent.com/7648499/31515928-eecbc474-af64-11e7-8fed-8cd888783786.png)

**Comment by kgf** [comment]
Sorry for the confusion. The error was when editing an existing training event.

**Comment by ThomasCarlson** [comment]
The issue was when you go to the *edit* page ...
if originally Training, then course and instructor should show.
if originally *not* Training, then course and instructor not show.

https://github.com/ReadyResponder/ReadyResponder/pull/552
