### ISSUE TITLE
Entering a repair should update the item

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#537]
When entering a repair, you can describe the repair, but that's it. This change would add a `Condition` field to the Repair model. It should have the same choices as `Condition` an Item has. When you save a repair, it should set the condition of the item to the same condition as indicated on the repair.

This will need further refinement in the future, because an item may need  more than one repair at a time. For now, this will improve the UX.

**Comment by dusty-wil** [comment]
@kgf I'm interested in looking in to this! Does this mean that the repair database table is going to need a new field also, or should the repair update the item only?

**Comment by kgf** [comment]
Hmm, good question. My instinct is that we'll want that extra information. ( How did this item get to the condition.) Let's still call it `condition`.

**Comment by dusty-wil** [comment]
@kgf sorry for the delay on this... I had to step back to deal with some school stuff this week. If this is time sensitive and you want to assign it to someone else please feel free, otherwise I'll likely be able to look at it this weekend!

**Comment by kgf** [comment]
NP, things happen. This weekend will be fine. Thanks for your help! And also thanks for the update !

**Comment by dusty-wil** [comment]
@kgf Ok, so I've created the table field, and when I save a repair I can see the condition is saved with the repair. However, I'm not sure how to update the repair status for the item. Should I be accessing the item's properties through the repair's controller? Is there another spot where this kind of update happens so I can get a general idea of how that should work?

**Comment by kgf** [comment]
I would probably approach it in the Repair controller. You'll probably want to create a method in the Item to calculate it's condition, which would get called whenever a repair is created or updated. This method would find all it's repairs that did not have a condition of `Ready`, then set the item to the worst of those conditions.
I hope that's clear, feel free to ask questions.
Thanks for your help,
Kevin

**Comment by dusty-wil** [comment]
Thanks @kgf, that is clear. I've got the method created and it can update the item's condition, but I'm wondering, should the method instead update the condition of the item to the most recent service date? IE if an item's in "In Service - Maintenance" I can add a repair that changes the item's state to "Ready" ... or maybe I'm not understanding how the repair should work?

**Comment by kgf** [comment]
Repair would track one issue from start to finish. 
Say I have a truck. I create a repair to have the inspection sticker updated. It would have a condition of`In service-Degraded` I then make a second repair, flat tire, `Out of service`. When the tire gets fixed, the condition of that repair is`ready`. be But the item condition should go back to degraded. That repair issue is still open.

**Comment by dusty-wil** [comment]
I see, so it's like you're "peeling off" layers of disrepair. it goes back to in service-degraded because you fixed the tire issue, but the inspection issue is still there.

**Comment by kgf** [comment]
Right, and they could be in any order. The condition of the item is the worst condition of all it's repairs.

**Comment by dusty-wil** [comment]
@kgf thanks for all your help, I think I've finally got it! One question about the DB field: I added a migration file to add the condition field to the repair table, should I include this with the commit?

**Comment by kgf** [comment]
Yes, it's needed to make it work.
