### ISSUE TITLE
Events should show timecards.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#538]
There are currently several tabs on an event, for things like tasks and availabilities. We would like to also have a tab for timecards, after notifications. It should show all timecards whose timespans overlap the event. The view should include the ability to verify them. This portion can be easily accomplished by using the table from the person#show view.

**Comment by goldenhub77** [comment]
@kgf I can take this

**Comment by kgf** [comment]
@goldenhub77 You're a machine !!
