### ISSUE TITLE
Convert all tests to RSpec

### ISSUE THREAD

**Issue by marnen** [ReadyResponder/ReadyResponder#54]
As discussed with @kgf , I'm going to attempt to convert the whole test suite to RSpec.

**Comment by marnen** [comment]
- [x] Upgrade to RSpec 3
- Convert Test::Unit to RSpec
  - [x] unit
  - [ ] functional (replace with Cucumber?)
- [ ] Refactor specs

**Comment by marnen** [comment]
For the RSpec 3 upgrade, I'm using the procedure documented at https://relishapp.com/rspec/docs/upgrade.

**Comment by kgf** [comment]
Thanks for your help @marnen !
