### ISSUE TITLE
Create a rack task to handle stale timecards

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#544]
People sometimes forget to sign out. Then the remember a few days from now, and sign out then. This results in a timecard with 100 hours. While I would also like validation on timecards, this is a request for a rake task to put any incomplete timecards into an error state after 24 hours. Please do not put much logic in the rake task itself, as they are difficult to cover in tests. 

For bonus points, pull the number of hours from a setting in the database. This would also want a migration to create the setting, and an addition to seeds.rb.

**Comment by nesteves** [comment]
Hello, I would like to help with this.

For the migration, we're not going to change the database structure here, just add a new setting right? Something like:

```ruby
Setting.create name: 'Timecard hour limit', description: '..', key: '..', value: 24, 
```

Can you also elaborate on the timecard validation?

**Comment by kgf** [comment]
Great, you're going for the bonus!
The setting should be retrieved from the database using the key only. Something like `timecard_maximum_hours` maybe...
Thanks for your help

**Comment by vcavallo** [comment]
Adding myself here as a backup contributor in case @nesteves drops out or would like a hand 👋

**Comment by kgf** [comment]
@vcavallo Could I interest you in a different issue ? Is there an area of software development that interests you ? There are additional improvements to RR that are not yet documented. I am happy to create a issue tailored to your interests. 
We appreciate your interest.
Kevin

**Comment by vcavallo** [comment]
@kgf very cool!
Most of my experience is in Rails and TDD/BDD. I'm entirely competent on the front end, but typically prefer back end. Happy to take a gander at whatever you've got ;)
