### ISSUE TITLE
When someone is available, assign them if appropriate

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#547]
Currently, an Event has tasks, a Task has requirements, a Requirement has assignments. An Assignment is the join between a Requirement and a Person, showing they are expected to fulfill that requirement. Currently, individual volunteers can use text messages to communicate with RR. This is great because then you don't need to manage logins. They can text in that they are available during an event.

What we would like is for requirements to have a new attribute, `auto_assign`, as a boolean. If true, the Person listed in the Availability will be checked to see if they meet the requirements of the Requirement. If they do, an additional check will be made to see if the Requirement is already full. If not full, an Assignment record should be made automatically.

The person should be notified of this, but this first effort does not need to include this. It is optional.

This first iteration can assume that only one Requirement will have auto-assign enabled. A second future issue will deal with the logic of how to fill multiple auto-assign requirements.

**Comment by himanshukgp** [comment]
I want to take up this issue.

**Comment by kgf** [comment]
Excellent, thanks @himanshukgp !
Post here if you have any questions.

**Comment by kgf** [comment]
@himanshukgp Do you have any questions ? Are you having any success ?

**Comment by kgf** [comment]
@himanshukgp We haven't heard from you in quite a while. Perhaps you got too busy to be able to help us ?
I'm going to set this issue back to help wanted. If this is a mistake, if you actually are working on it, please let me know, and I can switch it back again.
Thanks for your interest
Kevin

**Comment by bgates** [comment]
The 1st para of the issue lays out several models & relationships, then says a person "can text in that they are available during an event". The next says "the Person listed in the Availability will be checked to see if they meet the requirements of the Requirement" - but how is an Availability connected to a Requirement? The only foreign key in the availabilities table is person_id.

**Comment by kgf** [comment]
I found that you do not want to tie an availability directly to an event, or a requirement. People say they are available, and then you give them assignments to fit the needs of the event(s). There could be more than 1 event happening simultaneously. 
So, you're correct that there isn't a direct link from Availability to Requirement. 
You would need to look at the event referenced in the Availability message. Then look at the requirements for that event. ( I believe yo can get all of them as an association ) Also get the Person sending the message. Now compare the requirements with the title of the person.
Does that help ? Are you interested in this issue, @bgates  ?

**Comment by bgates** [comment]
I am interested @kgf, but I'm still confused. Are you saying the Availability description field (assuming the status field is 'Available') should be an exact match for an Event's description? What if it isn't? Can that happen in both the Availability creation and update?

**Comment by kgf** [comment]
Currently the Availability does not retain the knowledge of the keyword used. It probably should.
Take a look at this code, see if that helps.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/services/msg/available.rb#L13

**Comment by bgates** [comment]
I'm still confused by _you do not want to tie an availability directly to an event_ vs _You would need to look at the event referenced in the Availability message_. The service code looks like an availability is tied directly to an event, by the `event_codename`.

**Comment by kgf** [comment]
Availabilities can be `Available` or `Unavailable`. This means people can have three statuses for an event, Available, Unavailable, or Unknown. But their status at the event is based only on the fact that the time of the event and the time of the Availability overlap.
People can text (sms) in an Availability in two ways. They can say `available biscuit` or `available custom 2017-10-31 18:30 2017-10-31 23:30`. As you can imagine, people prefer the former. When they text `available biscuit`the code looks up the event having that codeword to get the times, but that's the end of the association. 
We do not want to tie Availability and Events in a has_many style Rails association. Sometimes it helps to have real world examples. 
First case would be that we ask people to sign up for one event, and then we end up doing something else. We once had a training event, but when the day came, we had a tropical storm. (It ended up being a just-in-time training !) If the Availabilities had been tied to the event, it would have made it difficult.
The second example is even more common. We frequently have more than one event at a time. We want you to state when you are willing to donate your time. We'll then pick requirements for you to fill. We may need you to bounce from one event to the other, because you can fill a requirement in one and then the other. You don't care, you're there to help.

The service code currently ties an `Availability` to an `Event` only until the Availability is created. The only link after that is that the times overlap.
I hope this helps. I'll check in again to see if you have follow-up questions.
