### ISSUE TITLE
When entering a repair, the repairer should be limited to active people

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#557]
Currently it shows all people

**Comment by rakesh-verma-16** [comment]
I'd like to work on this one.

**Comment by kgf** [comment]
@rakesh-verma-16 great ! Feel free to post questions.

I haven't reproduced it yet, but someone also reported a bug in this area of the code last night. They said they entered a repair, and when they saved it they got an error screen. 

 Thanks for your help.

**Comment by Atul9** [comment]
@kgf Can you please share the error screen ? 
I tried to reproduce it & found that all the persons are displayed in the repairer dropdown rather than only the active ones. 
@kgf I would like to submit a PR for this.
