### ISSUE TITLE
Display dates and editor on availability

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#560]
On many show pages, there is a footer that shows the created_at, edited_at and last_editor. This is not present on availability, but we'd like it to be.
This is an example from a different page
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/item_categories/show.html.erb#L17
Any questions feel free  to ask.

**Comment by Atul9** [comment]
I would like to take this.

**Comment by kgf** [comment]
@Atul9 Thanks for your help.
Feel free to ask questions as needed.
