### ISSUE TITLE
Add messages to recipients

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#578]
Currently we have notifications, and it's good. Each notification has many recipients. The notification also has channels, which define how to send the message. Currently, the only channel available is text message, but we're adding email. When a notification is activated, it walks through the recipients and looks up the content on how to reach them. We then connect to Twilio and send the message.

This issue is looking to capture the return values from the call to Twilio. There is already a Message class to contain this info. Each recipient will have many messages. Each message will belong to a recipient. 

This line is where you can first get a handle on the message.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/services/message/send_notification_text_message.rb#L25

You can look here for further documentation. => https://www.twilio.com/docs/api/messaging/send-messages

Thanks for your help !

**Comment by bgates** [comment]
@kgf it looks like the `#sms_send` method could return a `Twilio::REST::RequestError`; should that return value be handled differently than a normal return from the call to Twilio, or should the Message class get either one regardless?

**Comment by kgf** [comment]
@bgates Would you like to claim this issue ? 
I would still create the message either way. The message model has a status, that could be set to `error`.
Here is the schema
https://github.com/ReadyResponder/ReadyResponder/blob/development/db/schema.rb#L293
Thanks for your help !
