### ISSUE TITLE
When creating a task, make `Active` the default status

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#583]
Currently the status is blank. People are unlikely to create anything *except* active tasks.

**Comment by hmasila** [comment]
@kgf I can take this one if it is still available

**Comment by kgf** [comment]
That would be great, thanks @hmasila !

**Comment by hmasila** [comment]
@kgf There are two approaches to this. I will push both on different commits. One is having a before save callback, the other is setting the default in the schema definition. Your pick

**Comment by kgf** [comment]
Actually, I was expecting a default value in the controller, in the new action. This way, `Active` would be already chosen when the form loads.
Does that make sense ?

**Comment by hmasila** [comment]
@kgf I set `Active` to the value that is selected by default when the form loads as well. Check here https://github.com/ReadyResponder/ReadyResponder/pull/584/files#diff-3fcd4699f54a801714ffbf1674439654L7

**Comment by hmasila** [comment]
I think you might consider refactoring your code. The `Active` and `Cancelled` statuses only appear in the views and are not used anywhere else. The Task::STATUS_CHOICES_ARRAY does not even include `active`. Is this by design? @kgf

**Comment by kgf** [comment]
I absolutely have spots I would like to improve the code. For example, I would like to move some of the choices into Settings. I also want to consider Internationalization.

That's why I appreciate people helping with these pull requests.

**Comment by kgf** [comment]
Closed by #584
