### ISSUE TITLE
It would be nice to have a button to move from one event to the next

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#589]
The "Next" one would be defined by chronological order.
Previous would be good to make it consistent.

**Comment by valterbarros** [comment]
Do I want to do this, ok?

**Comment by valterbarros** [comment]
Where is the place for this button? on show from the event?

**Comment by valterbarros** [comment]
Do what you think about this one?

`Event.where('start_time > ?', Event.first.start_time).order(:start_time).first`

**Comment by kgf** [comment]
`Event.where('start_time > ?', Event.first.start_time).order(:start_time).first`
The problem I see is that it does not reference the one you're on. 
Right now we have an event for Halloween, and another for Friday. If I'm on the Halloween event, the `Next` link would take me to the Friday event; not the events in December.
]The button should be on the event#show action.
Does that make sense ?
Thanks for your help.
Kevin

**Comment by valterbarros** [comment]
Yeah @kgf I know your question. But notice that I put a `first` to take the latest first event.

**Comment by kgf** [comment]
In you PR, it references `self` which is what I expected.

**Comment by valterbarros** [comment]
Hahah yeah, really

**Comment by kgf** [comment]
It would be nice to use blue buttons similar to the blue + on the events page.
Thanks for your help!
Kevin

**Comment by valterbarros** [comment]
I Created a new PR with the button. and functionality to jump next and the previous event.
