### ISSUE TITLE
Police view does not show divisions

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#59]
There should be two narrow columns for attribs division 1 and division 2. These columns should be click to sort.

**Comment by pragyajalan** [comment]
All the peoples views use the same view page - Police, Cert, Active.. So if we add it to the Police view, it will get added to all those pages as well. It that ok?

**Comment by pragyajalan** [comment]
https://github.com/ReadyResponder/ReadyResponder/pull/188

**Comment by kgf** [comment]
Closed by PR #188 
Thanks Pragya !
