### ISSUE TITLE
A task does not show the address

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#595]
Which makes it hard to use. You have to edit the task to show the address on the form.

**Comment by Atul9** [comment]
@kgf I added a task & navigated to show page. I found that it shows the address i.e. the street name, city & state below the description. Can you please specify where is address not shown?

**Comment by kgf** [comment]
I took a look, and this line is the issue
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/tasks/show.html.erb#L23
We had a call out this past week. People did not take the time to look up zip code, for example, which suppressed all of the address. Only entering the street would be a common use case.
Thanks for your help, @Atul9 !
Kevin

**Comment by Atul9** [comment]
@kgf Do you suggest to have only @task.street.present? condition to display the address ?

**Comment by kgf** [comment]
We should probably show whatever we have. Although having the town only would be unusual, and having the state only would be silly.

**Comment by kgf** [comment]
@Atul9 Would you still be willing to help with this ?

**Comment by AdManteza** [comment]
@kgf Can i take a stab at this one?

**Comment by AdManteza** [comment]
@kgf I took a quick peek at the codebase. Couple of suggestions...

a.) Maybe we can require `street` and `city` for the `Task` model?
b.) After the `task` form is submitted, we can make a custom hook to somehow populate the `latitude/longitude`(~thru geolocation gem? cant remember exactly~ we already have it), using the street and city. If the user can provide a zip code(optional though), geolocation would be much more accurate. But at the very least we can generate the map properly.

Thoughts?

**Comment by kgf** [comment]
I would prefer not to require the street or city. In many cases, the end users will be involved in only one town, meaning 90% of their tasks will be in that town. Requiring that field would force unnecessary data entry. I would prefer an approach of displaying whatever you have available.
Thanks for your help!
Kevin

**Comment by kgf** [comment]
On point number two, there is a different issue for the Geo coding. We may have someone looking into that.

**Comment by AdManteza** [comment]
@kgf 
Copy that. 
I'll just refactor the way we display the complete address in the view to account for missing data(e.g. street, zip code...). 
I'll spin up a PR for it if its ok with you.

**Comment by kgf** [comment]
That's great, thanks !

**Comment by kgf** [comment]
Closed by #703
