### ISSUE TITLE
QR Code should not include birthdate at all

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#604]
The QR code currently includes birth date, but that is not needed, and should remain private.

**Comment by kgf** [comment]
@kurotyan514 would you be willing to tune this by removing the date of birth. It was found to be to much personal information.

**Comment by tungla** [comment]
This issue is fixed, just close it @kgf

**Comment by kgf** [comment]
I am confused by your comment, @tungla  This line suggests to me that the birthdate would still be part of the QR code.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/services/vcard/generator.rb#L18
Do you see it differently ?

**Comment by MattW216** [comment]
Hi, @kgf I'm interested in taking a look at this.

**Comment by kgf** [comment]
That would be great, Thanks @MattW216
