### ISSUE TITLE
Id_code validation on notification does not work for blank id_codes

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#605]
It should not check if the id_code is blank.

**Comment by kgf** [comment]
This line has the validation that needs to change
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/notification.rb#L24

**Comment by goldenhub77** [comment]
Fixed notification bug #652  and event creation test bug #654

**Comment by kgf** [comment]
This should be fixed by #652
