### ISSUE TITLE
edit availability erases person and changes person choice to 'Yes' 'No'

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#610]
When editing an availability, the Person field should still show original person.  Person field choices should be a list of active personnel. 
Currently, choosing edit and making any change erases the person's name and choices become blank, 'Yes' or 'No' and it fails validation.

**Comment by yasirazgar** [comment]
Looking into it.

**Comment by kgf** [comment]
@yasirazgar Thanks !
Adding on it what the OP said, the list of people should be all active, plus the original person, if editing. If someone becomes inactive,editing one of their availabilities would otherwise be impossible.

**Comment by yasirazgar** [comment]
ok @kgf I will make sure that only active persons are displayed in the drop down, this issue occurs when there is some error while updating the availability and edit is rendered.
