### ISSUE TITLE
On item index view, show last inspection

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#613]
It would be good to know what needs an inspection.

**Comment by saltmade** [comment]
@kgf Interested in taking this one on! Can I get access to the slack for relevant questions?

**Comment by kgf** [comment]
Sure, what email for invite ? 
I certainly want to meet you where is easiest for you, but I also like to have info here so others can follow along.

**Comment by saltmade** [comment]
@kgf jeff@jgheaton.com, but I'll ask questions here then!

**Comment by saltmade** [comment]
@kgf Is 'last inspection' going to be a required field?

**Comment by kgf** [comment]
Last inspection will actually not be a field at all. Inspection belongs to an item. An item has many inspections. So you would want to look up the inspections for the item, and give the most recent date from those inspections. Watch for N+1 queries. Also, inspections could be cancelled, so don't count those.
Thanks for your help!

**Comment by saltmade** [comment]
@kgf Does it make sense to include the last inspection on `/items` since it's not in the navigation? Should it be in `/item-types/:id`?

**Comment by kgf** [comment]
You are correct ! Good catch !

**Comment by jefheaton** [comment]
Addressed in https://github.com/ReadyResponder/ReadyResponder/pull/638

**Comment by kgf** [comment]
Closed by #638 
Thanks for your help.
