### ISSUE TITLE
Allow notifications to be created without being tied to an event.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#653]
Currently notifications can only exist if they're tied to an event.

**Comment by kgf** [comment]
Any interest @goldenhub77 ?

**Comment by goldenhub77** [comment]
@kgf Sure I can be a part of this. Do you have any thoughts about how you would like the UI implemented?

**Comment by kgf** [comment]
We already have a notifications index, so that's good enough for now. It lists the event in that index, which may break if the event is nil.
Add a blue plus button like we have in the event UI on the notification index page would be where I would start.
Thanks for your help !

**Comment by kgf** [comment]
Fixed by #660
