### ISSUE TITLE
System should indicate lack of departments when attempting to add users to tasks

### ISSUE THREAD

**Issue by masukomi** [ReadyResponder/ReadyResponder#662]
if an event has no departments there will be no users in the list when attempting to associate them with a task.

instead of presenting an empty user list the system should display a message indicating that you will not be able to associate anyone until departments have been associated with the event.

**Comment by kgf** [comment]
I have no problem with this being a simple validation that there must be one department chosen.

**Comment by AdManteza** [comment]
@kgf Can i take this one?

**Comment by kgf** [comment]
I believe that got covered other work. We're now requiring departments, so we no longer need to indicate.

**Comment by kgf** [comment]
I am closing this issue. We now require departments as a validation for saving an event.
