### ISSUE TITLE
Nickname attribute does not appear on the Person forms.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#664]
Some people have a nickname that they prefer to their legal name. We store this, and display it in most cases. Somewhere we lost the field on the edit form. It should be restored.

**Comment by farrahD** [comment]
@kgf can I work on this issue?
Is it in the /app/views/users/_form.html.erb file?

**Comment by kgf** [comment]
I would like to have added just after 
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/people/_form.html.erb#L6
You may need to whitelist it in the controller as well. 
If you have time to add a test, that would be excellent !
Thanks for your help.
Kevin

**Comment by kgf** [comment]
Sorry, just before that line.....

**Comment by farrahD** [comment]
Okay, so I'm having some issues setting up the project, specifically step 6 ii. iii. & iv.

**Comment by kgf** [comment]
Sorry for the delay @farrahD. Many of the contributors are based on the East Coast of America, and have been affected by the recent storms. We should be more responsive now.
What issues are you having ? Error messages ? If I'm reading it correctly, you're having trouble with Postgres ?

**Comment by farrahD** [comment]
Its okay, thanks for getting back to me when you could.
I'm having trouble setting up the local database. While in the ReadyResponder directory, when I run:
$ sudo -i -u postgres
> sudo -i -u postgres sudo: unknown user: postgres

Ps. If it matters, I'm on a mac.
I made sure I had the correct version of Ruby and have the latest versions of sqlite, postgres, and imagemagick@6

**Comment by kgf** [comment]
I just merged a PR from @houhoulis that removes the need for SQLite. I'll update the docs. 

In the mean time, you'll need to start PG by issuing `pg_ctl -D /usr/local/var/postgres start`
I don't think you need the sudo command for this.
See if that helps. 
Thanks for your help !
Kevin

**Comment by farrahD** [comment]
Thank you, I figured it out and got the server up and running after some trial and error.
Can the nickname attribute use :label => 'Nickname', similar to the syntax for first and last name?

**Comment by kgf** [comment]
Yes, that should be good.

**Comment by kgf** [comment]
Fixed by #680 and #681
