### ISSUE TITLE
Event's Availability tab doesn't display partially available people

### ISSUE THREAD

**Issue by masukomi** [ReadyResponder/ReadyResponder#666]
Users will expect partially availabile people to be displayed in the availability tab. This does not happen. 

`Event#responses` currently uses `Availability#containing` instead of `Availability#overlapping` 

`events/shown.html.erb`  has 

```
        <%= render(:partial => "availabilities/availabilities_table",
                   :locals => { :availabilities => ( @event.responses +
                                Assignment.active.for_time_span(@event.start_time..@event.end_time)),
                                :partial_availabilities => ( @event.partial_responses)} ) \
                                 || "No Availabilities yet !" %>
```

So, either  `@event.responses` should be replaced with `Availability#overlapping`  _or_ `@event.responses` needs to be modified to use `Availability#overlapping`

**Comment by kgf** [comment]
@masukomi Is this closed by your recent PR ?

**Comment by goldenhub77** [comment]
@kgf refer to pr #692 for this resolution. I made note that event.rb and availability.rb will be refactored in the future to make it more DRY and logical.

**Comment by kgf** [comment]
This is no longer an issue
