### ISSUE TITLE
new_item_type page errors when accessed through admin panel

### ISSUE THREAD

**Issue by saltmade** [ReadyResponder/ReadyResponder#687]
**Description** :octocat:
When trying to add a new item type through the admin panel, the page errors out because there is no 

**Reproduction guide** 🐞
Start ReadyResponder
go to admin panel at the top
Click "Item Types"
Click New

**Observed behaviour**: 👀 💔
<img width="893" alt="screen shot 2018-04-03 at 11 15 16" src="https://user-images.githubusercontent.com/3383824/38258387-541eb0e0-3730-11e8-973d-fcb3f7e8ea19.png">

**Expected behaviour**: ❤️ 😄
See new item type page with option to choose a category

**System Info** 💻
OS: OSX
ReadyResponder: 2.8.0

**Comment by yasirazgar** [comment]
Fixing it.
