### ISSUE TITLE
Items need to have department

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#69]
Items could belong to the highway department or the Department of Public Works. The item should know what department it belongs to.
This should be a required field. Department should be a new object.
Department menu can go under admin

**Comment by houhoulis** [comment]
@kgf An interesting idea is to add the specs for what you are asking for.  See https://medium.com/@kentcdodds/first-timers-only-78281ea47455.

@DJG86g don't wait though.  Just an idea that was on my mind, I'm not obligating @kgf  :smile:
