### ISSUE TITLE
Unable to edit assignments due to requirement_id not being present

### ISSUE THREAD

**Issue by goldenhub77** [ReadyResponder/ReadyResponder#696]
Files that will need to be modified: 
app/controllers/assignments_controller.rb
app/views/assignments/_form.html.erb
app/views/assignments/edit.html.erb

**Comment by kgf** [comment]
Fixed by #698 
Thanks @goldenhub77  !

**Comment by goldenhub77** [comment]
@kgf  It turns out there is a conflict when editing or creating a new assignment simply using just one _form so I created explicit forms for the edit and new actions in the controller until a better solution is determined.

**Comment by kgf** [comment]
Thanks for your response. Could you elaborate on the conflict ?

**Comment by kgf** [comment]
And I'm good with an expedient interim solution !
