### ISSUE TITLE
When there are no availabilities, Report - Calendar Chart fails to load

### ISSUE THREAD

**Issue by goldenhub77** [ReadyResponder/ReadyResponder#699]
undefined method `to_datetime' for nil:NilClass

def self.process_data
    availabilities = Availability.available
    **start_time = availabilities.map(&:start_time).min.to_datetime**
    end_time = availabilities.map(&:end_time).max.to_datetime
    data = []
    data <<
      (start_time..end_time).map do |date|
        count = Availability.where('date(start_time) <= ? AND date(end_time) >= ?', date, date).count

**Comment by kgf** [comment]
Fixed by #700 
Thanks @goldenhub77
