### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by houhoulis** [ReadyResponder/ReadyResponder#70]
To make it more inviting for new contributors to get involved, it's good to reduce the barriers to entry as much as possible.  I forget where I saw this first discussed, but basically, it's good to give people the positive experience of an accepted PR rather than bringing up obstacles _that could have been avoided_ by providing requirements & guidance up front.

The convention seems to be to add a `CONTRIBUTING.md` file, (e.g. [rails](https://github.com/rails/rails/blob/master/CONTRIBUTING.md), [rust](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md), [rubygems](https://github.com/rubygems/rubygems/blob/master/CONTRIBUTING.rdoc), [factory-girl-rails](https://github.com/thoughtbot/factory_girl_rails/blob/master/CONTRIBUTING.md)).  Then link to it in the README.

Requirements and general guidance can help whether someone is reporting an issue or coding.  Specifically for coders, we can add anything that would help their PR get accepted.

E.g. if we want to suggest (or require) `rubocop` review, we can add the [`.rubocop.yml`](https://github.com/bbatsov/rubocop#configuration) file to the repo.  One benefit is the contributor can work on their code without waiting for human response, until they know that the PR won't (shouldn't) be rejected for style / complexity / etc. issues.  Maybe we can add that requirement to CONTRIBUTING.md and then configure the `.rubocop.yml` file to trim down to a minimal level of requirements?

I like providing feedback on PRs if that's what contributors want, so perhaps the CONTRIBUTING.md could say "if you would like detailed feedback, add flag "feedback welcome" to your PR".

**Comment by kgf** [comment]
@houhoulis Is this resolved by the recent PR 106 ?
