### ISSUE TITLE
Remove Return to Event button

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#701]
I would like to eventually eliminate the blue menus on the left hand side of the navigation. One step towards this would be to remove the `Return To Event` from the forms. The PR should limit itself to this scope.

**Comment by kgf** [comment]
Thanks @patel-atis

**Comment by patel-atis** [comment]
I’m interested!

**Comment by kgf** [comment]
@patel-atis Are you still interested in this ? That would be great !

**Comment by kgf** [comment]
Partially rsolved by #702

**Comment by kgf** [comment]
This should include revising any tests affected.

**Comment by sa77** [comment]
@kgf i can work on this if it is open .. which form is it because `/events/1/edit` does not have that button ?

**Comment by kgf** [comment]
Thanks for your help! This would be from task show and requirement show. It may also be on assignment show, but I can't look right now.

**Comment by sa77** [comment]
@kgf i think they're already resolved from this PR https://github.com/ReadyResponder/ReadyResponder/pull/702/files

**Comment by kgf** [comment]
@sa77 You  are correct, it is closed by #702 . Can we interest you in something else ? If you have an tech interest, we may have an issue for it.
Thanks for your help.
Kevin

**Comment by sa77** [comment]
@kgf yes sure
