### ISSUE TITLE
Add "Application Date" to Person

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#71]
Please add a field for 'application date' to person.  Field should be date format.  

Story:
This is to record when a new person has applied for the department.  The field exists on the application form and would help us track if an application stalls.

**Comment by kgf** [comment]
It should also include a date picker

**Comment by avinoth** [comment]
I'd like to do this. Any takers already?

**Comment by kgf** [comment]
Go for it, that would be great.

Thanks for your help !
