### ISSUE TITLE
Everybody view lacks icon to add new person

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#713]
The view Everybody, in the drop down for People, does not have an add person button.

Operationally, end-users are frequently on this page, checking that a new contact has not already been added before entering their information.  An add person button would be very useful.

The button needed appears on the All Active People view, which appears when People is chosen from top bar.

**Comment by PatODay** [comment]
Just opened a PR to add this feature to the `Everybody` view
