### ISSUE TITLE
Notifications#index does not show a date in the listing

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#717]
This makes it very hard to use !

**Comment by vsrnth** [comment]
hi @kgf I'll take this.

**Comment by kgf** [comment]
@vsrnth That would be great, thanks. Let us know if you need help.

**Comment by vsrnth** [comment]
@kgf How do I got about I joining the ReadyResponder slack? 
There's no way to sign up.

**Comment by kgf** [comment]
Send me an email at kfallon@readyresponder.org
I'll use the address to sign you up. Please include your GitHub handle in the subject

**Comment by vsrnth** [comment]
![screenshot_2018-10-04 all notifications](https://user-images.githubusercontent.com/6362618/46456287-f22b1b80-c7cb-11e8-8ebd-9e7cbf4d1c23.png)

Couple of queries:
- So I'm expected to add a date column to the right of the table?
- Which date needs to be displayed? The date on which the notification was created/last modified?

**Comment by kgf** [comment]
For now, yes, please just use the date created. There may be references in the code to support scheduling notifications for the future, but that is not yet implemented.
Please put it as the first column, all the way on the left.
Thanks for your help!
Kevin
