### ISSUE TITLE
Convert event navigation from blue side buttons to bread crumbs

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#735]
I would like to remove the side navigation eventually. We can convert to bread crumbs across the top. There are some examples of this already.. 
Example
Event > Task > Requirement > Assignment
Shelter > Medical Intake > EMT > John Doe
All the bread crumbs should be links to that point in the tree.
There tests may need to be adjusted.
Please do not make one huge PR.
@sa77 might this be of interest?

**Comment by sa77** [comment]
@kgf yes sure .. i'll do it

**Comment by sa77** [comment]
@kgf the buttons that are links to index and show pages can be converted to breadcrumbs but there are 'Edit event', 'New task', 'New assignment' buttons on the side navigation .. leave them as is ?

**Comment by kgf** [comment]
Yes, leave those as is. Separate effort. We'll use the blue plus sign for the new stuff, find a blue pencil for the edit.

**Comment by kgf** [comment]
Closed by #737 
Thanks @sa77
