### ISSUE TITLE
Cancelled Assignments still count for the colored summary boxes.

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#751]
Cancelled assignments should not affect the count.
These are the boxes I am referring to....
<img width="207" alt="Screen Shot 2019-05-26 at 8 39 18 PM" src="https://user-images.githubusercontent.com/2431417/58389243-b9f47980-7ff6-11e9-99cf-7f4ad8612d3d.png">

**Comment by kgf** [comment]
I suspect the issue is in this area of code. It does not consider the status of the assignment when calculating people.
https://github.com/ReadyResponder/ReadyResponder/blob/2a1d1bb99c532923a8239f3b9c4609a37b70e298/app/models/event.rb#L21

**Comment by goldenhub77** [comment]
@kgf - I ran some preliminary tests and believe this can be fixed by adding a scope on the has_many
has_many :assignments, -> { where(status: ['New', 'Active']) }, :through => :requirements
