### ISSUE TITLE
Items need to be more flexible

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#79]
One of the prime reasons to track items is to be able to accurately account for their use during a disaster. Different configurations of items will garner different reimbursement rates. I see three scenarios.
1. The easy one... A thing is used as is. An example is a towable lighting unit. We track it as an item. it has serial numbers, it has no accessories. It is self-contained.
2. A group... For example, we might have a Ford F350 truck, which is reimbursed at a specific rate. If it has a plow attached, it is a different rate. If it has a sander, it is a different rate. And if it has a plow and a sander it is another rate. Oh, it's a 9 foot plow ? Different rate ! In this scenario, we will track the accessories, such as the sander and the plow.
3. The equivalent of M&Ms... We can be reimbursed for the use of traffic cones, but we don't want to track each cone, that's too much work. "Hey, we need to find Cone 42 and 743 ! Start looking..." is not likely. If at the end of an event we know we started with 50 cones and we end with 50 cones, that's good enough. I am currently thinking this would be a group of 50, like scenario 2. I could create 50 cone records, but not concern myself with which is which.

**Comment by kgf** [comment]
I realize I did not summarize here. I think we can use `Item` and `ItemGroup` I think that things that are in a group are not available. If you want to use them, use the group, or break it up.

**Comment by houhoulis** [comment]
What are "M&Ms"?

**Comment by houhoulis** [comment]
For scenarios 1) and 2), rather than "ItemGroup", would a concept like "usage" make sense?

``` ruby
# There's got to be a better name than Usage
class Usage
  has_many :items
  belongs_to :timecard
  belongs_to :event #  :through => :timecards
end
```

Where `items` can be singular (scenario 1) or plural (scenario 2).

I suggest this because in 2) you are talking about an _application_ of items.

I am not seeing the value of the group except for its application at a specific event, or even a shift at the event.  Would a group have value in some other way?

(Perhaps by providing a way to track items that depend on each other in a different context than an event?  ... That could be a different model though.)

**Comment by kgf** [comment]
Staying with the snowplow use case, a truck would get a plow and a sander in the late fall. Unless something broke, they would stay together for the season.
M&Ms are a small hard candy that melts in your mouth, not in your hand. They are all the same (except for the green ones) and you don't usually count them individually.

**Comment by kgf** [comment]
I need to research this further

**Comment by kgf** [comment]
The inventory has been implemented with items having both a qty field and the ability to add Unique IDs. So for a vehicle, you would enter the name `Car 54`, some unique ids, like the VIN and the license plate and a qty of 1
For less critical items, like a floodlight, you might have one item record with a qty of four, but then have all four serial numbers as unique ids in this record.
Although I'm closing this issue, the concept of grouping has not yet been addressed.
