### ISSUE TITLE
Implement fullCalendar or equivelent for events

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#8]
http://arshaw.com/fullcalendar/docs/event_data/Event_Object/

**Comment by kgf** [comment]
On the index page for events, it should show a calendar, with the datatable list below that. Fullcalendar is one option, http://dhtmlx.com/docs/products/dhtmlxCalendar/ would be another. It is not required that drag and drop work for this PR, just that it accurately displays the events, and that the entries on the calendar are links to the event.

**Comment by TerryBeyak** [comment]
I've experience with FullCalendar, and I can try and tackle this if that's all right?

**Comment by kgf** [comment]
That would be awesome,. If you have any questions, please ask is.

Thanks for your help.

**Comment by Spandana-Sai** [comment]
@TerryBeyak  Are you working on this issue? Can you please let me know

**Comment by kgf** [comment]
The library chosen should have a AGPL compatible license.
