### ISSUE TITLE
Item belongs_to Grant

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#84]
When a grant is awarded, information often needs to be tracked. When was the grant awarded, when does it sunset, and what items were acquired with it ?

This will require a new object model, Grant.
name:string A short bit of text that will be used in the views and in the selection choices on forms
description:text A longer decription that can go into details.

Items will need to be modified to include the grant_id.

**Comment by kgf** [comment]
This is mainly a CRUD update. 
**name:string** A short bit of text that will be used in the views and in the selection choices on forms
**description:text** A longer description that can go into details.
**start_date:date** When did we receive these items
**end_date:date** When are we no longer responsible for these items

The show form should show a table of the items in this grant.
The index should show the name, the dates, and perhaps a count of the items included

**Comment by pcofilada** [comment]
@kgf Just for clarification the Grant model is not yet existing right?

**Comment by kgf** [comment]
Correct. You are rocking ! So this would also require some changes to the item model, and the item show and edit form. The item form should show the grant title, and that title should be a link to the grant. The grant#show should have a datatable with all the items included in the grant.

**Comment by pcofilada** [comment]
Great! I will look into this after finishing  some other issues.

**Comment by pcofilada** [comment]
@kgf do you have any mockup on how will it look like on frontend?

**Comment by kgf** [comment]
Not currently. I would expect there would be CRUD resources for grants. The index of grants would fall under the "Admin" section of the menu. When editing/creating an item, you would have a dropdown for Active grants. `Active` should be a value for the `status` field on Grants.

Does that help, @pcofilada  ?

**Comment by caironoleto** [comment]
I'm working on this issue.

**Comment by caironoleto** [comment]
ops, has a opened pull request. I will look another issue.

**Comment by sa77** [comment]
@kgf looks like an old issue opened in 2016 .. i would like to help out on this if it still open

**Comment by kgf** [comment]
@sa77 That sounds great ! Do you have any questions ?

Thanks for your help !
Kevin

**Comment by sa77** [comment]
@kgf i'm setting up the app for dev now .. i'll let you know once i get started.

**Comment by kgf** [comment]
If you notice anything missing from the seeds.rb, there is a separate issue for that. Might catch two with one effort !
https://github.com/ReadyResponder/ReadyResponder/issues/110
