### ISSUE TITLE
Source attribute on Items should be changed to Vendor

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#88]
It is currently changed in the form as a new label, but I would prefer it to be changed on the backend, in the database.

**Comment by kgf** [comment]
This would require a change to the Item model to give it a pointer to a new model.
**name:string**
**street:string**
**city:string**
**state;string**
**zipcode:string**
**status:string**
**comments:text**

There are two paths for info such as phone and email. One is to add a few columns for phone and email. The other is to make the **channel** model polymorphic, and shared with the person model.
http://www.informit.com/articles/article.aspx?p=2220311&seqNum=6

**Comment by jacklynhma** [comment]
can I grab this one?

**Comment by kgf** [comment]
@jacklynhma thanks for your help!

**Comment by kgf** [comment]
@jacklynhma has opened a WIP PR, #571

**Comment by kgf** [comment]
@jacklynhma How's it going ? Anything I could help with ?
