### ISSUE TITLE
Code of Conduct links on home page on GitHub are broken

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#92]
This is a bug outside of LIMS itself.  On the home page in GitHub, the Code of Conduct links display a 404 error.
This will not encourage contributors to read the Code of Conduct.

**Comment by houhoulis** [comment]
Thank you for reporting this.  I would say the bug is definitely in LIMS: it's not user-facing in a running installation of LIMS, but it's world-facing on GitHub  :open_mouth:  It's our README and we need to fix it.

**Comment by VanAuken** [comment]
And thank you for the encouragement!
