### ISSUE TITLE
Inspection model needs connection to Person

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#94]
Inspection model needs connection to Person, should have a `belongs_to`.

**Comment by ChanChar** [comment]
I can also take this one. :]

**Comment by kgf** [comment]
That would be awesome, thanks. It should be as `inspector`. Look at `repairer` as an example.

Thanks for your help.

**Comment by ChanChar** [comment]
@kgf quick clarification, if im not mistaken the Inspection model already has a `belong_to` association to the Person model. Did we just want to change it so that the association to `inspector`?

**Comment by kgf** [comment]
That is correct, sorry for the confusion.

**Comment by VanAuken** [comment]
@ChanChar Are you still interested in resolving this issue?  Seems like you nearly had it with last PR.  Thanks for your interest.

**Comment by ChanChar** [comment]
@VanAuken hah yup. still interested. was caught up at work. will submit something by this week. 👍 thanks for the reminder!

**Comment by VanAuken** [comment]
@ChanChar That's great!  I appreciate it.

**Comment by kgf** [comment]
I am mentioning this on all the claimed issues. We always appreciate people's help, but if you could have PRs submitted by 1PM EST this Sunday, I'll have time to review and integrate them for a demo on Monday.

Thanks !
Kevin

**Comment by kgf** [comment]
@ChanChar do you still have any interest in this ? Perhaps you need this year's T-shirt !

Thanks
Kevin

**Comment by ChanChar** [comment]
@kgf haha oh man time flies. yup, i'll tackle this one.

**Comment by kgf** [comment]
Great, thanks.
