### ISSUE TITLE
Add groups to Gemfile

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#97]
Groups should be added to exclude gems that are not needed. This would speed up our test suite on Travis

**Comment by OrthoDex** [comment]
Hey @kgf , would it be alright if I issue a quick PR for this? It'll help me get a little more familiar with the project. Further, it'll help out other subsequent PRs.

Apart from adding groups, we could cache the dependencies as explained [here](https://docs.travis-ci.com/user/caching/), and run parallel tests if possible explained [here](https://docs.travis-ci.com/user/speeding-up-the-build/).

**Comment by kgf** [comment]
That sounds great to me. I've read some on the parallel builds, not the dependencies. (yet)
Thanks

**Comment by OrthoDex** [comment]
Hey @kgf , on further reading I found that caching and parallel tests are both currently available only for private projects :disappointed: 
Sorry about that.

**Comment by OrthoDex** [comment]
Hey @kgf , issued a PR at #204 . The test suite is failing on a nil class error. Pretty weird, I haven't touched any code that should affect the existing features.

**Comment by kgf** [comment]
I have started a re-run on the tests

**Comment by kgf** [comment]
fixed by #204
